### ISSUE TITLE
Upload of subtitles

### ISSUE THREAD

**Issue by ebbertd** [opencast-ilias/OpenCast#10]
**Use Case**

Opencast can handle subtitles, these can be processed and displayed in the player. A subtitle editor is in development.

**Desired implementation**

The upload of subtitles should be possible during the initial video upload, as well as afterwards for already published videos. Currently, the Opencast API does not support this. This Opencast PR needs to be merged first: https://github.com/opencast/opencast/pull/3670

**Comment by ferishili** [comment]
Closed as completed in #277, squashed and merged via https://github.com/opencast-ilias/OpenCast/commit/ff9a4639f797535e53da071084a5531cfa1e50aa
