### ISSUE TITLE
 Sort function (A-Z) does not work properly in the column "Owner" (5.0.0)

### ISSUE THREAD

**Issue by samuelinniger** [opencast-ilias/OpenCast#100]
**Describe the bug**
Sort function (A-Z) does not work properly in the column "Owner"
See screenshot below. 

**To Reproduce**
- Go to a Opencast Video Series in ILIAS
- Click on the Column title "Speaker"

**Expected behavior**
The metadata should be properly sorted A-Z. This is not the case.

**Screenshots**
<img width="1839" alt="grafik" src="https://user-images.githubusercontent.com/60101424/202743726-a55096e7-da18-494d-b615-ee398ca190d3.png">
**Log**
If you have it please attach the relevant log.

**Environment (please complete the following information):**
ILIAS version: v7.11 2022-06-29
Plugin version: 5.0.0
Browser: Firefox
Opencast: 11.0.0.

**Comment by dagraf** [comment]
After pulling PR https://github.com/opencast-ilias/OpenCast/pull/174 again, the bug does not exist anymore. Thx for the fix!
