### ISSUE TITLE
"Report Date modification", poor performance: +- 15 sec until message is transmitted (5.0.0)

### ISSUE THREAD

**Issue by samuelinniger** [opencast-ilias/OpenCast#106]
Describe the bug
Sending a "Date Modification" takes 15 seconds, after the user clicks on "send". Only then the user is re-directed to the content page of the video series.

To Reproduce

-     Activate the option "Enable Report Date Modification" in the plugin settings
-    Go to the opencast series, and click on the button "Report Date Modification" (only visible if there are scheduled events in the series)
-     Enter a message and click on send

Expected behavior
The user is promptly re-directed to the content page

Environment (please complete the following information):
ILIAS version: v7.11 2022-06-29
Plugin version: 5.0.0
Browser: Firefox
Opencast: 11.0.0.

**Comment by dagraf** [comment]
@okaufman I guess this is only due to the already existing bug https://github.com/opencast-ilias/OpenCast/issues/80. Or am I wrong?

**Comment by dagraf** [comment]
Does not appear anymore since fixing the performance issue https://github.com/opencast-ilias/OpenCast/issues/80.
