### ISSUE TITLE
Update to Paella Player 7

### ISSUE THREAD

**Issue by ebbertd** [opencast-ilias/OpenCast#11]
For version 7 of the Paella player it has been rewritten and now needs to be integrated into the plugin differently. See: https://github.com/polimediaupv/paella-core

**Comment by dagraf** [comment]
Here is the timeline for the release of PP7 Carlos Turro presented at the Opencast Summit 2022 (10.3.2022):

- Start: Early 2021
- First working releas: October 2021
- Field tests & improvments: Jan - June 2022
- OC inclusion: OC 12

If anyone has news about an update, please comment below.

**Comment by mliradelc** [comment]
Hello, It's my pleasure to inform that Paella Player 7 has now Matomo support. Now I'm making tests over this plugin.

**Comment by mliradelc** [comment]
If any wants to add their comments regarding the new plugin, please write here https://github.com/polimediaupv/paella-user-tracking/issues/5
