### ISSUE TITLE
Editing metadata of scheduled event: Recording Station and Date are not shown (5.0.0.)

### ISSUE THREAD

**Issue by samuelinniger** [opencast-ilias/OpenCast#110]
This only concerns editing matadata of scheduled events with the plugin settings: "Metadata of scheduled events editable: All, except date and recording station."

**Describe the bug**
When editing metadata of scheduled events, the fields "Recording Station" and "Date" are not shown.

**To Reproduce**
1. Set the Plugin settings to "Metadata of scheduled events editable: no".
<img width="246" alt="grafik" src="https://user-images.githubusercontent.com/60101424/203548662-cdf3a5fe-3ce6-48e6-8935-76aa463ab861.png">
2. Go to the opencast series, Actions --> Edit Metadata of an Scheduled event

**Expected behavior**
As in plugin version 3.7.5: The date and recording station of scheduled events should always be visible, but in this case locked/not editable.
--> see mousover in plugin version 3.7.5.
<img width="500" alt="grafik" src="https://user-images.githubusercontent.com/60101424/203551347-7242fafc-44bd-4cbd-abc8-1150ce9096cc.png">

**Screenshots**
<img width="500" alt="grafik" src="https://user-images.githubusercontent.com/60101424/203547821-0544a661-6e85-43fa-9cbf-d5e45846f751.png">

**Environment (please complete the following information):**
ILIAS version: v7.11 2022-06-29
Plugin version: 5.0.0
Browser: Firefox
Opencast: 11.0.0.

**Additional context**
Suggested solution: 
Make the section "scheduling" visible, but lock editing. 
The section "Scheduling" probably should be renamed to "Scheduled metadata" here . Reading "Scheduling", the user could have wrong editing expectations.

**Comment by dagraf** [comment]
Note: In plugin version 3.7.5 it is at the moment possible to edit recording station and date of scheduled live-events. This is a bug. So when fixing this issue, please make sure that:
1.  When in the plugin settings the option "Metadata of scheduled events editable" is set to "Metadata of scheduled events editable: All, except date and recording station."
2. For 'Scheduled events' and for 'Scheduled live-events/live-streams': The date and recording station of scheduled events should be visible, but in locked/not editable.

**Comment by dagraf** [comment]
**Note 2: Naming of section**
Please leave the english title "Scheduling". But add a proper german title. Suggestions: "Terminplanung" > Because at the moment when the language is set to german the sections is called "Scheduling".

**Comment by dagraf** [comment]
After deploying https://github.com/opencast-ilias/OpenCast/pull/118: I did a retest and the bug does not exist anymore.
