### ISSUE TITLE
Definable workflow parameters

### ISSUE THREAD

**Issue by ebbertd** [opencast-ilias/OpenCast#13]
**Use Case**

It should be possible to set workflow parameters not only to _true_. It should be possible to specify further workflow parameters as checkboxes.

**Desired implementation**

In addition to Boolean parameters, checkboxes, strings and numbers should be possible as workflow variables.

**Comment by dagraf** [comment]
Thanks for posting the idea. We have here common interests.

**Comment by ferishili** [comment]
As @reiferschris & I discussed about this, here are a concept (taken from Moodle Opencast Video Plugin) to apply for this issue with screenshots:

1. In settings, there is only an option to set the tags of those workflows to be provided to the teachers:
![Screenshot 2023-09-07 at 16 47 46](https://github.com/opencast-ilias/OpenCast/assets/53179227/010f8edb-5179-4ba4-8c6f-995b0506f617)

2. In the video table list, like the one currently in use, there will be an action that opens a dialog to select an already configured (via Tags above) workflow from a dropdown.
 
![Screenshot 2023-09-07 at 17 07 51](https://github.com/opencast-ilias/OpenCast/assets/53179227/58d7a645-830f-4744-8dd1-e6dcf718a957)

3. In the dialog, by selecting each workflow, its configuration panel is loaded and teachers are able to input values , which will be directly taken and passed to opencast to start that workflow with the user configs!
![Screenshot 2023-09-07 at 17 08 02](https://github.com/opencast-ilias/OpenCast/assets/53179227/0ad025b7-d391-46c6-9fdd-7ff2d3a852c4)


In this approach, there is no need to create/save/load the workflows from the plugin, and in fact the configuration panel for each workflow comes from opencast itself.
This approach can also be somehow integrated into the Workflow parameters section but it needs further discussion in the community.

**Comment by ferishili** [comment]
Hi @dagraf, thanks, that is a good point.
The first thing that came to my mind, and it is the easiest and most reliable, is that we could provide the localization for this feature. That means, you would only need to add the title into the language strings of the plugin in ILIAS with specific string ID for example:
`workflow_title_{retract}#:#Withdraw publication`

But we could also provide another way of intercepting the workflows, which is by having a specific table of settings to define the titles for those workflows: This would need a new db table and a few addition setting options and a setting page!

**Comment by dagraf** [comment]
The first idea of yours would be an option. But we were asking us the question, why the existing table could not be used. Is the missing translation in other languages the problem?

**Comment by ferishili** [comment]
I am actually almost dome with the implementation of this feature, and yes, you are right, we are going to use the existing table but boosted up with a few more items. The title remains, but the parameters will be removed, additionally there will be tags, roles and descriptions for that table.
