### ISSUE TITLE
Error, when saving settings of a series which was created in Opencast without metadata in the fields "Organizers" and "Contributors"

### ISSUE THREAD

**Issue by samuelinniger** [opencast-ilias/OpenCast#131]
**Describe the bug**
Errors in ILIAS, when saving settings of a series which was created in Opencast. 
The issue is related to the empty metadata in the fields "Organizers" and/or "Contributors". The errors are not shown, if the series in opencast was created with metadata in the two fields. 

What we also observe in ILIAS is that entries in the fields "Organizers" and "Contributors" seem to be fixed/permanent. They do not get updated via API, if there were changes in Opencast. So this issue could also be related to the caching behavior of the plugin. 

**To Reproduce**
1. Create a Series in OC, do not specify the Organizers and Contributors
2. Login to ILIAS, and create a new Series by choosing the option "Existing Series"
3. Go to "Settings", change something and click on "Save"
4. --> "An error occurred while communicating with the OpenCast-Server"

**Expected behavior**
Saving settings is also possible if the metadata-fileds "Organizers" and "Contributors" are empty.

**Screenshots**
Empty fields "Organizers" and Contributors"
<img width="1122" alt="grafik" src="https://user-images.githubusercontent.com/60101424/213750525-eb140757-c020-4dac-82ee-4749110471fa.png">

After clicking on "Save": 
<img width="582" alt="grafik" src="https://user-images.githubusercontent.com/60101424/213750654-ede340bf-fd5a-4465-b908-6d31b38c59ea.png">

**Log**
Error log in Opencast: /api/series/9a66da76-1a3b-4339-8caf-c86525f9e442/metadatajava.lang.IllegalArgumentException: Unable to parse Mixed Iterable value into a JSONArray:

**Environment (please complete the following information):**
 - ILIAS version:   (v7.16 2022-11-24) 
 - Plugin version: [5.0.3]
 - Opencast version [Opencast 12.0.0.SNAPSHOT - 6125b39 - gebaut am 2023-01-16)

**Comment by dagraf** [comment]
I did some further testing: This bug only exists, when in the new config-tab "Metadata" the fields for "creator" and "contributer" are set to "Read only". If "Read only" is NOT activated, it does not exist. This would be a workaround until the expected behavior is implemented.

**Comment by MichelleKubier** [comment]
Unfortunately, the workaround does not work for us. Regardless wether creator and contributor are set read-only or not, we cannot change metadata of the series, for example the title. Therefore the priority of this ticket is not low for us.
Plugin: OpenCast 5.1.0
ILIAS: 7.19

Error thrown with message "Call to a member function addToAcls() on null"

Stacktrace:
#10 Error in /data/html/webroot/ilu_7/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Series/class.xoctSeriesGUI.php:203
#9 xoctSeriesGUI:updateGeneral in /data/html/webroot/ilu_7/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:46
#8 xoctGUI:performCommand in /data/html/webroot/ilu_7/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:35
#7 xoctGUI:executeCommand in /data/html/webroot/ilu_7/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Series/class.xoctSeriesGUI.php:94
#6 xoctSeriesGUI:executeCommand in /data/html/webroot/ilu_7/Services/UICore/classes/class.ilCtrl.php:217
#5 ilCtrl:forwardCommand in /data/html/webroot/ilu_7/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php:156
#4 ilObjOpenCastGUI:executeCommand in /data/html/webroot/ilu_7/Services/UICore/classes/class.ilCtrl.php:217
#3 ilCtrl:forwardCommand in /data/html/webroot/ilu_7/Services/Repository/classes/class.ilObjPluginDispatchGUI.php:45
#2 ilObjPluginDispatchGUI:executeCommand in /data/html/webroot/ilu_7/Services/UICore/classes/class.ilCtrl.php:217
#1 ilCtrl:forwardCommand in /data/html/webroot/ilu_7/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /data/html/webroot/ilu_7/ilias.php:23

**Comment by dagraf** [comment]
Thanks for retesting. I changed the priority from "low" to "high". @chfsx: Could you please have a closer look at this bug and fix it if possible? Thx!

**Comment by dagraf** [comment]
@chfsx: There are several issues that might be related. So when taking a look, maybe also quickly check the following issues:
https://github.com/opencast-ilias/OpenCast/issues/140
https://github.com/opencast-ilias/OpenCast/issues/152 > appears only with OC-13 (therefore maybe also due to changes in Opencast)

**Comment by MichelleKubier** [comment]
Using Fabians pull request https://github.com/opencast-ilias/OpenCast/pull/155 this error still occurs

**Comment by chfsx** [comment]
Hi @MichelleKubier thanks for the feedback! would it be possible for us to look at this together via Discord a VC tool of your choice?
 
I can/could also reproduce this bug, but with the fix of the branch it is fixed for me, so we would probably have to debug together what is different with you that it still does not work.

Alternatively, you could send me a dump of all your OC plugin database tables in a secure way, so I could test it directly with your settings and your instance. but we would certainly have to discuss this by email and see how you could provide such a dump, since it also contains security-relevant data.

**Comment by dagraf** [comment]
After pulling PR https://github.com/opencast-ilias/OpenCast/pull/155 again, the bug does not exist anymore. Thx for the fix!
