### ISSUE TITLE
German traduction is missing: "Bestehende Serie" (Existing Series)

### ISSUE THREAD

**Issue by samuelinniger** [opencast-ilias/OpenCast#133]
**Describe the bug**
When creating a new series, the german traduction "Bestehende Serie" is missing

**To Reproduce**
1. Create a new Series

**Expected behavior**
--> Traduction "Bestehende Serie" is shown.

**Screenshots**
<img width="996" alt="grafik" src="https://user-images.githubusercontent.com/60101424/214624205-d64154b9-c55d-4b69-907c-2dee0f2092da.png">

**Environment (please complete the following information):**
 - ILIAS version: v7.11 2022-06-29
 - Plugin version: 5.1
 - Opencast version: 12
 - Browser: Firefox

**Comment by dagraf** [comment]
After pulling PR https://github.com/opencast-ilias/OpenCast/pull/162, the bug does not exist anymore. Thx for the fix!
