### ISSUE TITLE
When creating a new series, setting "View changeable" should be activated/pre-selected per default

### ISSUE THREAD

**Issue by samuelinniger** [opencast-ilias/OpenCast#135]
**Describe the bug**
When creating a new series, setting "View changeable" should be activated (i.e. pre-selected) per default, as it was in previous plugin versions.

**To Reproduce**
1. Create a new Opencast Series
2. go to settings

**Expected behavior**
The settings option "View changeable" should be activated per default.

**Screenshots**
In Plugin Version 5.1., "View Changeable" is deactivated.
<img width="993" alt="grafik" src="https://user-images.githubusercontent.com/60101424/214632594-87b130cf-74b4-4501-8c5a-9ef22639e4b2.png">

**Environment:**
    ILIAS version: v7.11 2022-06-29
    Plugin version: 5.1
    Opencast version: 12
    Browser: Firefox

**Comment by dagraf** [comment]
After pulling PR https://github.com/opencast-ilias/OpenCast/pull/173 again, the feature works as described above. Thx for the fix!
