### ISSUE TITLE
Expand plugin rights management

### ISSUE THREAD

**Issue by ebbertd** [opencast-ilias/OpenCast#14]
**Use Case**

Within the Opencast object it is desired by teachers to be able to set who can upload, schedule, record and download videos.

**Desired implementation**

In the rights settings of an object it can be set role-based who has access to which parts of the object, e.g. upload or delete. More options should be added for:

- Scheduling
- Recording via Opencast Studio
- Download

**Comment by dagraf** [comment]
Thx for coming up with this enhancement. We have common interests here.

**Comment by dagraf** [comment]
@reiferschris Could you specify how the desired implementation should look like in your opinion?

**Comment by dagraf** [comment]
See the following document for a first draft how the expanded plugin rights could look like: https://docs.google.com/document/d/1DGOjwiox84TcBc2NXGowJDLyu6R8pNPFoMp5_pShx7Y/edit?usp=sharing

**Comment by ferishili** [comment]
Closed as completed in #301, squashed and merged via https://github.com/opencast-ilias/OpenCast/commit/b00894480c4d9b68f3a67bbcf3a3534a5f626930
