### ISSUE TITLE
Scheduled events: New "Start" time & date is set, each time metadata is edited in ILIAS

### ISSUE THREAD

**Issue by samuelinniger** [opencast-ilias/OpenCast#141]
**Describe the bug**
Each time medata of a scheduled event ist edited in ILIAS, the current date & time is set as "Start"-Time.
(the technical time of the scheduling is not affected, i.e. the time the recording will start on the capture agent)

**To Reproduce**
1. Create a scheduled event in Opencast
2. In ILIAS, click on "Edit metadata" --> "Save" (with or without editing metadata)
3. The plugin overwrites the "Start" date&time (meta data field in Opencast: «Startdatum») of the planned scheduling with the current date&time.

**Expected behavior**
The "Start"-time stays the same (--> Start time of the recording on the capture Agent).

**Screenshots**
<img width="1096" alt="grafik" src="https://user-images.githubusercontent.com/60101424/219729794-7a8d34dd-8feb-410c-941f-d0b9dc4c7e03.png">

<img width="581" alt="grafik" src="https://user-images.githubusercontent.com/60101424/219729943-64467bbe-aa78-45f4-942d-d528a5a0adff.png">

**Environment (please complete the following information):**
 - ILIAS version: 7.18
 - Plugin version: 5.1.0
 - Opencast version 12.0
 - Browser: Firefox

**Additional context**

**Comment by okaufman** [comment]
I checked the curl.log for what was sent when updating an event. Here is an example:
```
    [metadata] => [{"label":"EVENTS.EVENTS.DETAILS.CATALOG.EPISODE","flavor":"dublincore\/episode","fields":[{"id":"creator","value":[" Olivia Kaufmann"]},{"id":"title","value":"Test2 change "}]}]
    [scheduling] => {"agent_id":"IDTest_021_ext352","start":"2024-07-17T20:58:00Z","end":"2024-07-17T21:10:00Z","inputs":["Channel A","Channel B"]}
```
    
 Inside of the metadata-array, there is no startDate or startTime given. The time inside of the scheduling-array is correct. Does opencast always need a startTime, when updating the metadata? Is there a setting we can change on the opencast-server to fix this?

**Comment by dagraf** [comment]
I tested the fix https://github.com/opencast-ilias/OpenCast/issues/141: Issue does not longer appear. Therefore, I close this ticket.
