### ISSUE TITLE
Use the "start" date as default for the sorting order of events in series, instead of the "created" date

### ISSUE THREAD

**Issue by samuelinniger** [opencast-ilias/OpenCast#143]
**Describe the bug**
There are some issues with the "default" sort order of series, i.e. the sort order displayed to the user when the series is first accessed. Currently, there is no preselected (active) sorting. 

The plugin seems to use the "created" date for the initial sorting order, and not the "start" date.
This leads to some problem/issues with scheduled events: the "created" date of scheduled events is the "start" date of the first event (of the scheduled event series).
If a video is uploaded in a series containing scheduled events (e.g. created a few days before), the video will be displayed at the very end of the series. The user then will not find the event at the expected position, when looking at the "start" dates. 

We suggest to change the default to sort by "start date", instead of "created" date

**To Reproduce**
1. Create a series in ILIAS.
2. Go to Opencast, schedule a few events. One starting right now/ in a few minutes).
3. Go to ILIAS, upload a video manually
--> the uploaded video will appear at the end of the video series

**Expected behavior**
Default sorting order is by "Start date".

**Screenshots**
Bug: ---> the manual uplaod is shown at the very end

<img width="1131" alt="2023-02-21_18-12-01" src="https://user-images.githubusercontent.com/60101424/220414259-af9bdaff-5d31-49aa-bfe0-b66d19c9ade5.png">

We suggest to use the sorting order "Start" date as default: 

<img width="1128" alt="2023-02-21_18-13-13" src="https://user-images.githubusercontent.com/60101424/220414468-51947f06-d88a-4d39-8e24-470dcc1884e8.png">

**Environment (please complete the following information):**
    ILIAS version: 7.18
    Plugin version: 5.1.0
    Opencast version 12.0
    Browser: Firefox

**Comment by dagraf** [comment]
I tested the fix https://github.com/opencast-ilias/OpenCast/pull/145: Issue does not longer appear. Therefore, I close this ticket.
