### ISSUE TITLE
Course-ID/Titles are not set anymore in the metadata field "Organizers" of a opencast-series, when using the internal API for automated scheduling

### ISSUE THREAD

**Issue by samuelinniger** [opencast-ilias/OpenCast#144]
**Describe the bug**
When using the internal API for automated scheduling (specific Uni Bern use case), the info "Course-ID/Course Title" is not transferred anymore to opencast. The metadata field "Organizers" remains empty.

**Expected behavior**
See screenshot: ILIAS Course ID/Title should be shown 

**Screenshots**

First line: with OC-Plugin version 5.1.0.
Second line: with OC Plugin version 3.7.X
<img width="1264" alt="2023-02-22_18-11-25" src="https://user-images.githubusercontent.com/60101424/220706437-d29bc8ad-5b98-4515-b1ea-7895c8cec55e.png">

**Environment (please complete the following information):**
ILIAS version: 7.18
Plugin version: 5.1.0
Opencast version 12.0
Browser: Firefox

**Additional context**
Info on the internal API of the plugin: https://github.com/opencast-ilias/OpenCast/blob/bdbdceaa534501b55b1b748a776b9bcbd96cdc66/classes/Service/README.md

**Comment by dagraf** [comment]
After deploying #146: We did some testing and can confirm the bugfix. Thx!
