### ISSUE TITLE
Usage of detailed Opencast ACLs

### ISSUE THREAD

**Issue by ebbertd** [opencast-ilias/OpenCast#15]
**Use Case**

Currently, only roles with read and write permissions can be specified in the object settings. No further distinction can be made.

**Desired implementation**

For each role it is possible to specify which rights should be associated with this role. These are of course read and write. In Opencast, however, other actions can also be defined, such as annotate for the annotation tool. It should be possible to specify all of them.

**Comment by dagraf** [comment]
@reiferschris Could you specify how the desired implementation should look like in your opinion?

**Comment by reiferschris** [comment]
I'm not even sure anymore what the intention of this issue was, therefore I close this.
