### ISSUE TITLE
ErrorException thrown with message: Directory not empty

### ISSUE THREAD

**Issue by fsesterh** [opencast-ilias/OpenCast#151]
**Describe the bug**
When uploading a video we always get the following error:

Whoops\Exception\ErrorException thrown with message "rmdir(/data/ilias/data/thkilu/temp/opencast/c4a323d8-2af3-4d17-93d4-5ce3f1e83919): Directory not empty"

Things to note:
- the upload does not fail, the video is uploaded but this error is thrown
- the folder is empty after the upload

**To Reproduce**
1. Create an OpenCast Object
2. Select a video file to upload
3. Fill out all mandatory fields
4. Save

**Expected behavior**
No such error should be thrown.

**Screenshots**

**Log**
If you have it please attach the relevant log.

**Environment (please complete the following information):**
 - ILIAS version: 7.16
 - PHP version: 7.3
 - Plugin version: 5.1.0
 - Opencast version: ?
 - Browser: Firefox

Stacktrace:
Stacktrace:
#17 Whoops\Exception\ErrorException in /data/html/webroot/ilu_7/libs/composer/vendor/league/flysystem/src/Adapter/Local.php:420
#16 rmdir in /data/html/webroot/ilu_7/libs/composer/vendor/league/flysystem/src/Adapter/Local.php:420
#15 League\Flysystem\Adapter\Local:deleteDir in /data/html/webroot/ilu_7/libs/composer/vendor/league/flysystem/src/Filesystem.php:252
#14 League\Flysystem\Filesystem:deleteDir in /data/html/webroot/ilu_7/src/Filesystem/Provider/FlySystem/FlySystemDirectoryAccess.php:206
#13 ILIAS\Filesystem\Provider\FlySystem\FlySystemDirectoryAccess:deleteDir in /data/html/webroot/ilu_7/src/Filesystem/FilesystemFacade.php:102
#12 ILIAS\Filesystem\FilesystemFacade:deleteDir in /data/html/webroot/ilu_7/src/Filesystem/Decorator/FilesystemWhitelistDecorator.php:110
#11 ILIAS\Filesystem\Decorator\FilesystemWhitelistDecorator:deleteDir in /data/html/webroot/ilu_7/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Util/FileTransfer/UploadStorageService.php:72
#10 srag\Plugins\Opencast\Util\FileTransfer\UploadStorageService:delete in /data/html/webroot/ilu_7/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventGUI.php:601
#9 xoctEventGUI:create in /data/html/webroot/ilu_7/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:46
#8 xoctGUI:performCommand in /data/html/webroot/ilu_7/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventGUI.php:228
#7 xoctEventGUI:performCommand in /data/html/webroot/ilu_7/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventGUI.php:200
#6 xoctEventGUI:executeCommand in /data/html/webroot/ilu_7/Services/UICore/classes/class.ilCtrl.php:217
#5 ilCtrl:forwardCommand in /data/html/webroot/ilu_7/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php:176
#4 ilObjOpenCastGUI:executeCommand in /data/html/webroot/ilu_7/Services/UICore/classes/class.ilCtrl.php:217
#3 ilCtrl:forwardCommand in /data/html/webroot/ilu_7/Services/Repository/classes/class.ilObjPluginDispatchGUI.php:45
#2 ilObjPluginDispatchGUI:executeCommand in /data/html/webroot/ilu_7/Services/UICore/classes/class.ilCtrl.php:217
#1 ilCtrl:forwardCommand in /data/html/webroot/ilu_7/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /data/html/webroot/ilu_7/ilias.php:23

**Comment by fsesterh** [comment]
Size of the video does not matter. Tested with a weboptimized Big Buck Bunny test-file; around 21MB.

**Comment by dagraf** [comment]
@fsesterh Since we can not recreate this issue: Could you please test this fix (https://github.com/opencast-ilias/OpenCast/pull/155)? Thx!

**Comment by fsesterh** [comment]
I'll add it to my pipeline and will try if I can get the PR to work for me. Will report back.

**Comment by dagraf** [comment]
There was a misstyping in the PR #155 (see comment https://github.com/opencast-ilias/OpenCast/pull/155#issuecomment-1514879687). Which means this issue is not fixed yet. Therefore @fsesterh, you can postpone the testing of the fix.

**Comment by dagraf** [comment]
Now this issue should be fixed. Therefore and since we can not reproduce this issue: @fsesterh, could you please test this fix (https://github.com/opencast-ilias/OpenCast/pull/158) and report your findings? Thx!

**Comment by fsesterh** [comment]
Retest on https://github.com/srsolutionsag/OpenCast/tree/fix/151 OK.

**Comment by fsesterh** [comment]
Still needs the merge though :)

**Comment by dagraf** [comment]
Thx for testing. Merging will be done after @ralede was able to test https://github.com/opencast-ilias/OpenCast/issues/152.
