### ISSUE TITLE
Error message after changing the series metadata

### ISSUE THREAD

**Issue by ralede** [opencast-ilias/OpenCast#152]
**Describe the bug**
After creating a series, an error message appears when you change the metadata

**To Reproduce**
1. create a new opencast object
2. create a new series or choose an existing one
3. click on save
4. try to change the metadata (e.g. title)
5. the error message appears

**Expected behavior**
successful change of the metadata

**Log**
Error thrown with message "Call to a member function addToAcls() on null"

Stacktrace:
#10 Error in /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Series/class.xoctSeriesGUI.php:203
#9 xoctSeriesGUI:updateGeneral in /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:46
#8 xoctGUI:performCommand in /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:35
#7 xoctGUI:executeCommand in /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Series/class.xoctSeriesGUI.php:94
#6 xoctSeriesGUI:executeCommand in /var/www/ilias/Services/UICore/classes/class.ilCtrl.php:217
#5 ilCtrl:forwardCommand in /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php:156
#4 ilObjOpenCastGUI:executeCommand in /var/www/ilias/Services/UICore/classes/class.ilCtrl.php:217
#3 ilCtrl:forwardCommand in /var/www/ilias/Services/Repository/classes/class.ilObjPluginDispatchGUI.php:45
#2 ilObjPluginDispatchGUI:executeCommand in /var/www/ilias/Services/UICore/classes/class.ilCtrl.php:217
#1 ilCtrl:forwardCommand in /var/www/ilias/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /var/www/ilias/ilias.php:23

-- GET Data --

ref_id                   : 8538
cmd                      : post
cmdClass                 : xoctseriesgui
cmdNode                  : ql:qc:1a3
baseClass                : ilobjplugindispatchgui
fallbackCmd              : updateGeneral
rtoken                   : 6343ca842fb59020d69acc479a47963a
lang                     : de
limit                    : 50

-- POST Data --

form_input_2             : testserie20230314b
form_input_3             : 
form_input_4             : Testraum Rainer
form_input_5             : Rainer Ledermann
form_input_8             : 
form_input_9             : 0
form_input_11            : checked

-- Files --

empty

-- Cookies --

ilClientId               : iliastest
PHPSESSID                : b7e9io1c3rcb1qecb7eog0hvpj
1197938969               : {"any_entry_engaged":true,"tools_engaged":false,"more_available":false,"entries":{"0:0":[0,0,0],"0:1":[0,1,0],"0:1:1":[0,0,0],"0:1:2":[0,1,0],"0:2":[0,0,0],"0:2:1":[0,0,0],"0:2:2":[0,0,0],"0:3":[0,0,0],"0:4":[0,0,0],"0:5":[0,0,0],"0:6":[0,0,0],"0:7":[0,0,0],"0:7:0":[0,0,0],"0:7:1":[0,0,0],"0:7:3":[0,0,0],"0:7:4":[0,0,0],"0:7:5":[0,0,0],"0:7:6":[0,0,0],"0:7:7":[0,0,0],"0:7:9":[0,0,0],"0:7:10":[0,0,0],"0:8":[0,0,1]},"tools":{"696c48656c704753546f6f6c50726f76696465727c68656c70":[0,0,1,"T:0"]},"known_tools":["696c48656c704753546f6f6c50726f76696465727c68656c70"],"last_active_top":"0:1"}

-- Session --

_authsession_authenticated: 1
_authsession_user_id     : 624
_authsession_expired     : 0
referer_ref_id           : 8538
tbl_limit                : 50
help_screen_id           : root/view_content/view_content.1
help_search_term         : 
SessionType              : 2
orig_request_target      : 
lang                     : de
ILIAS\Init\StartupSequence\StartUpSequenceDispatcher_passed: 1
il_pd_history            : 
pditems_0_blnav          : ::0
pdtasks_0_blnav          : ::0
pdnews_0_blnav           : ::0
pdmail_0_blnav           : ::0
awrn_last_update         : 1678800818
awrn_nr_users            : 0
awrn_nr_husers           : 0
il_rep_mode              : flat
il_rep_ref_id            : 1
il_nav_history           : a:2:{s:5:"8538:";a:7:{s:2:"id";s:5:"8538:";s:6:"ref_id";s:4:"8538";s:4:"link";s:110:"ilias.php?ref_id=8538&cmd=showContent&cmdClass=ilobjopencastgui&cmdNode=ql:qc&baseClass=ilobjplugindispatchgui";s:5:"title";s:18:"testserie20230314a";s:4:"type";s:4:"xoct";s:10:"sub_obj_id";s:0:"";s:9:"goto_link";s:0:"";}s:5:"8108:";a:7:{s:2:"id";s:5:"8108:";s:6:"ref_id";s:4:"8108";s:4:"link";s:79:"https://ilias-test.hrz.uni-bonn.de/goto.php?target=grp_8108&client_id=iliastest";s:5:"title";s:15:"Testraum Rainer";s:4:"type";s:3:"grp";s:10:"sub_obj_id";s:0:"";s:9:"goto_link";s:0:"";}}
table                    : Array
                         (
                             [tbl_xoct_9328] => Array
                                 (
                                     [624] => Array
                                         (
                                             [offset] => 0
                                         )
                         
                                 )
                         
                         )
                         
referer                  : /ilias.php?ref_id=8538&cmd=editGeneral&cmdClass=xoctseriesgui&cmdNode=ql:qc:1a3&baseClass=ilobjplugindispatchgui

-- Server/Request Data --

PATH                     : /usr/local/bin:/usr/bin:/bin:/usr/local/lib/nodejs/node-v16.13.1-linux-x64/bin
USER                     : www-data
HOME                     : /var/www
HTTP_COOKIE              : ilClientId=iliastest; PHPSESSID=b7e9i (SHORTENED FOR SECURITY); 1197938969={"any_entry_engaged":true,"tools_engaged":false,"more_available":false,"entries":{"0:0":[0,0,0],"0:1":[0,1,0],"0:1:1":[0,0,0],"0:1:2":[0,1,0],"0:2":[0,0,0],"0:2:1":[0,0,0],"0:2:2":[0,0,0],"0:3":[0,0,0],"0:4":[0,0,0],"0:5":[0,0,0],"0:6":[0,0,0],"0:7":[0,0,0],"0:7:0":[0,0,0],"0:7:1":[0,0,0],"0:7:3":[0,0,0],"0:7:4":[0,0,0],"0:7:5":[0,0,0],"0:7:6":[0,0,0],"0:7:7":[0,0,0],"0:7:9":[0,0,0],"0:7:10":[0,0,0],"0:8":[0,0,1]},"tools":{"696c48656c704753546f6f6c50726f76696465727c68656c70":[0,0,1,"T:0"]},"known_tools":["696c48656c704753546f6f6c50726f76696465727c68656c70"],"last_active_top":"0:1"}
HTTP_TE                  : trailers
HTTP_SEC_FETCH_USER      : ?1
HTTP_SEC_FETCH_SITE      : same-origin
HTTP_SEC_FETCH_MODE      : navigate
HTTP_SEC_FETCH_DEST      : document
HTTP_UPGRADE_INSECURE_REQUESTS: 1
HTTP_REFERER             : https://ilias-test.hrz.uni-bonn.de/ilias.php?ref_id=8538&cmd=editGeneral&cmdClass=xoctseriesgui&cmdNode=ql:qc:1a3&baseClass=ilobjplugindispatchgui
HTTP_DNT                 : 1
HTTP_ORIGIN              : https://ilias-test.hrz.uni-bonn.de
HTTP_CONTENT_LENGTH      : 947
HTTP_CONTENT_TYPE        : multipart/form-data; boundary=---------------------------179223976915823417503173642101
HTTP_ACCEPT_ENCODING     : gzip, deflate, br
HTTP_ACCEPT_LANGUAGE     : de,en-US;q=0.7,en;q=0.3
HTTP_ACCEPT              : text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
HTTP_USER_AGENT          : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
HTTP_HOST                : ilias-test.hrz.uni-bonn.de
REDIRECT_STATUS          : 200
SERVER_NAME              : ilias-test.hrz.uni-bonn.de
SERVER_PORT              : 443
SERVER_ADDR              : 131.220.212.138
REMOTE_PORT              : 12305
REMOTE_ADDR              : 131.220.19.25
SERVER_SOFTWARE          : nginx/1.14.2
GATEWAY_INTERFACE        : CGI/1.1
HTTPS                    : on
REQUEST_SCHEME           : https
SERVER_PROTOCOL          : HTTP/2.0
DOCUMENT_ROOT            : /var/www/ilias
DOCUMENT_URI             : /ilias.php
REQUEST_URI              : /ilias.php?ref_id=8538&cmd=post&cmdClass=xoctseriesgui&cmdNode=ql:qc:1a3&baseClass=ilobjplugindispatchgui&fallbackCmd=updateGeneral&rtoken=6343ca842fb59020d69acc479a47963a
SCRIPT_NAME              : /ilias.php
CONTENT_LENGTH           : 947
CONTENT_TYPE             : multipart/form-data; boundary=---------------------------179223976915823417503173642101
REQUEST_METHOD           : POST
QUERY_STRING             : ref_id=8538&cmd=post&cmdClass=xoctseriesgui&cmdNode=ql:qc:1a3&baseClass=ilobjplugindispatchgui&fallbackCmd=updateGeneral&rtoken=6343ca842fb59020d69acc479a47963a
SCRIPT_FILENAME          : /var/www/ilias/ilias.php
PATH_INFO                : 
FCGI_ROLE                : RESPONDER
PHP_SELF                 : /ilias.php
REQUEST_TIME_FLOAT       : 1678800823.0738
REQUEST_TIME             : 1678800823

-- Environment Variables --

empty

**Environment (please complete the following information):**
 - ILIAS version: v7.18 2023-02-01
 - PHP version: 7.3
 - Plugin version: 5.1.0
 - Opencast version 13.0.0 (educast.nrw)
 - Browser: firefox, chrome

**Additional context**
the same message also appears when using the development branch

**Comment by dagraf** [comment]
Thank you for reporting. Can you please post your configuration of the "Series metadata" (see plugin config tab "Metadata", subtab "Series"?

**Comment by ralede** [comment]
![series_metadata](https://user-images.githubusercontent.com/118901635/228822236-acb7fa29-72cb-4a78-8157-cce9fb5a2ce5.jpg)

Here is a screenhot of the series metadata

**Comment by dagraf** [comment]
@ralede: Since we are not yet on OC-13: Could you please test the fix https://github.com/opencast-ilias/OpenCast/pull/155? Thx!
