### ISSUE TITLE
Series without "Creator" and "Contributer" can not be created

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#157]
**Describe the bug**
If I have configured the metadatas "Creator" and "Contributor" as NOT "Required" and as NOT "Read-Only" (see screenshot) I can not create a series which has no text in the fields "Creator" and "Contributor". The following error message appears: 
"An error occurred while communicating with the OpenCast-Server: Unable to parse Mixed Iterable value into a JSONArray:"

**To Reproduce**
1. Check if you have configured your Plugin as shown in the screenshot below
2. Create a series in ILIAS, set a title and delete the prefilled text in the fields "Creator" and "Contributor"
3. Hit on save

**Expected behavior**
If configured accordingly it should be possible to create a series without specifying a creator or contributor

**Screenshots**
See screenshot of configuration of "Series Metadata":
<img width="856" alt="Bildschirmfoto 2023-04-24 um 18 18 25" src="https://user-images.githubusercontent.com/15246287/234056471-b9b5bce4-8ce0-41a7-87eb-09f2e606026d.png">

**Environment (please complete the following information):**
 - ILIAS version: v7.20 2023-04-05
 - Plugin version: 5.1.0
 - Opencast version 12

**Additional context**
Bug exist with and without #155 
The bug also exists if I have configured all series metadata without any prefilled information and leave "Creator" and "Contributor" empty.

**Comment by dagraf** [comment]
@chfsx Could you please take a look again at the issues concerning metadata of series? This bug also exists on our productive ILIAS-Installation and is therefore pretty urgent...

**Comment by chfsx** [comment]
Yes, sure, I'll look at it again. I was able to reproduce the error in my case, but I fixed it with PR #155. so now I have to see why it continues to occur in certain cases. I may need new exports of the database tables from you to be able to recreate this exactly. I will contact @okaufman  about this if necessary.

**Comment by chfsx** [comment]
the relevant part of the fix in 155 is here: 
https://github.com/opencast-ilias/OpenCast/pull/155/files#diff-8c02c256dffdff6878142cad02c249b801a7a846c8d7b2dd47c71f06b41c4d84R33-R53

**Comment by okaufman** [comment]
I think the problem ist that when creating a series jsonSerialize() from MetadataField.php is used. 
jsonSerialize() from src/Model/Series/Request/UpdateSeriesMetadataRequestPayload.php is only used, when an already created Series is being updated.

**Comment by dagraf** [comment]
After pulling PR https://github.com/opencast-ilias/OpenCast/pull/155 again, the bug does not exist anymore. Thx for the fix!
