### ISSUE TITLE
Required ILIAS Producers group

### ISSUE THREAD

**Issue by ebbertd** [opencast-ilias/OpenCast#16]
Error description

In the object's settings, it is mandatory to specify a group in which users are enrolled to be able to edit videos - the so-called _Ilias Producers_. This assumes that Opencast is used in a certain way. However, it is possible to use the plugin without using this group.

Desired solution

The specification of a group for _Ilias Producers_ should be optional.

**Comment by dagraf** [comment]
Thx for reporting. I totally agree with your desired solution.
