### ISSUE TITLE
Update from 5-1-0 to 5-1-1 crashes and refers to migration

### ISSUE THREAD

**Issue by fsesterh** [opencast-ilias/OpenCast#169]
**Describe the bug**
After updating the plugin codebase from 5.1.0 (commit: https://github.com/opencast-ilias/OpenCast/commit/cd519604eb04b9b40363b5bcf3cf73227ded0021 ) to 5.1.1 (commit: https://github.com/opencast-ilias/OpenCast/commit/b868b95c3256cfa0f24e9c6f86dd1da9bb0de229 ) I get the follwing error when updating the plugin via ILIAS administration:

ilPluginException thrown with message "You try to update from a incompatible version of the plugin, please read the infos here: https://github.com/opencast-ilias/OpenCast/blob/main/doc/migration.md"

**To Reproduce**
1. Update codebase from 5.1.0 to 5.1.1 (see above for commit details)
2. Login to ILIAS and access plugin admin GUI
3. Update the plugin

ILIAS 7.22
PHP 7.4
MariaDB 10.6

Plugin Version 5.1.1
Plugin-DB Version: 39

**Expected behavior**
Plugin is updated and works.

**Log**
[q9fjm_6232.log](https://github.com/opencast-ilias/OpenCast/files/11719826/q9fjm_6232.log)

**Environment (please complete the following information):**
 - ILIAS version: [e.g.  v7.6 2022-01-26]
 - PHP version: [e.g. PHP 7.4.3]
 - Plugin version: [e.g. 4.0.0]
 - Opencast version [e.g 11.0.0]
 - Browser: [e.g. chrome, safari]

**Comment by mjansenDatabay** [comment]
See: https://github.com/ILIAS-eLearning/ILIAS/commit/85469ff1318ceaae7f83a1ab476d9ee44f1f4193

**Comment by ferishili** [comment]
Hi @mjansenDatabay,
would you describe how it could be related to this issue or what should we get from that commit? Thanks
> See: [ILIAS-eLearning/ILIAS@85469ff](https://github.com/ILIAS-eLearning/ILIAS/commit/85469ff1318ceaae7f83a1ab476d9ee44f1f4193)

**Comment by mjansenDatabay** [comment]
Hi @ferishili ,

sorry, maybe I was wrong. A colleague of mine sent me the following error ...

```bash
root@octa04-vm01:/srv/www/my.ilias.de/admin/ilias_errors# cat 83f24_1477.log
Whoops\Exception\ErrorException thrown with message "Class srag\DIC\OpenCast\Database\DatabaseDetector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (ilDBInterface::primaryExistsByFields)"

Stacktrace:
#2 Whoops\Exception\ErrorException in /srv/www/my.ilias.de/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/vendor/srag/dic/src/Database/DatabaseDetector.php:19
#1 Whoops\Run:handleError in /srv/www/my.ilias.de/ilias/libs/composer/vendor/filp/whoops/src/Whoops/Run.php:514
#0 Whoops\Run:handleShutdown in [internal]:0


-- GET Data --

ref_id                   : 31
admin_mode               : settings
ctype                    : Services
cname                    : Repository
slot_id                  : robj
pname                    : OpenCast
cmd                      : refreshLanguages
cmdClass                 : ilobjcomponentsettingsgui
cmdNode                  : 1d:m0
baseClass                : ilAdministrationGUI
```

... and pointed me to THIS issue here. Bug maybe this is a different problem. If yes, please ignore my comment.

**Comment by ferishili** [comment]
Thanks for your explanation. I would say, these are not related, and the reported log error must have a separate issue. As you would see, the PR for this issue is already out there and that solves the update crashing issue.

**Comment by dagraf** [comment]
Fixed with https://github.com/opencast-ilias/OpenCast/pull/186
