### ISSUE TITLE
Filters are not cleared when collapsing the filter menu

### ISSUE THREAD

**Issue by ebbertd** [opencast-ilias/OpenCast#17]
**Error description**

Set filters in the series object remain active when the menu for filtering is hidden. This can lead to the situation that users always see only a filtered table, because they do not realize that another filter is active.

**Desired solution**

In the case that users want to collapse the filter menu when a filter is still active, the users should be informed that this will remove the filter. Thus, closing the filter menu will remove all filters.

**Comment by dagraf** [comment]
Thx for reporting. I totally agree with your desired solution.

**Comment by dagraf** [comment]
With the changes in filtering from ilias6 to ilias7 active filters get indicated when the filter options get collapsed (see screenshot). I therefore close this issue. 

<img width="730" alt="Bildschirmfoto 2022-11-22 um 19 43 08" src="https://user-images.githubusercontent.com/15246287/203395760-fce6eb00-87a3-46da-89d3-6306d8351bcd.png">
