### ISSUE TITLE
Upload of (larger) videos stucks after 30 seconds (with slower internet connection)

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#176]
**Describe the bug**
The upload of a video stops after 30 seconds if a simulate slow internet connection.

**To Reproduce**
1. Limit your internet speed and click on button 'Upload Event'
2. Select a video file (approx. 50 MB and larger)
3. Video starts uploading
4. After 30 seconds the upload stops (shown by no longer growing progress bar, see also screenshot)

**Expected behavior**
Upload should work also with slow internet speed.

**Screenshots**
<img width="1069" alt="Bildschirmfoto 2023-07-03 um 10 53 26" src="https://github.com/opencast-ilias/OpenCast/assets/15246287/a9a41694-7fa0-4655-b595-53197caf7f7d">

**Environment (please complete the following information):**
 - ILIAS version: tested with 7.18 and 7.22 
 - Plugin version: tested with 5.1.0 and 5.1.1
 - Opencast version: tested with OC-12 and -13
 - Browser: Firefox

**Additional context**
We had a similar issue last year. See tickets:
https://github.com/opencast-ilias/OpenCast/issues/88
https://github.com/opencast-ilias/OpenCast/pull/122

**Comment by okaufman** [comment]
When using 2.4MBit/s upload speed the chunck size should be max 9MB, probably better 8MB. Right now the default size is 20MB. 
If we make the chunk size smaller, the upload will be slower in general.

**Comment by dagraf** [comment]
So we have to find a reasonable compromise. I would like to discuss this with the community and  will take this issue on the agenda of our todays meeting.

Speeking for the University of Berne: We have the community plugin up and running since January 2023 and have received no complaints of staff or students concerning the upload so far. Therefore, and because we believe most users will upload videos when using a WLAN or LAN connection, we would suggest to stay with the default size of 20MB.

**Comment by dagraf** [comment]
After community meeting: 

- On the ILIAS installation of the University of Bern values which were suspected to be responsible for the 30 seconds are set much higher (max_execution_time = max_input_time = 3600). Therefore, these 30 seconds seem to come from somewhere else.
- @chfsx: Please invest some time in analyzing which configuration of the ILIAS web servers leads to these 30 seconds.

**Comment by okaufman** [comment]
I found the file where the timeout is set. It's in libs/bower/bower_components/dropzone/dist/min/dropzone.min.js
There is a timeout of 30000 milliseconds (30 seconds)

**Comment by dagraf** [comment]
> I found the file where the timeout is set. It's in libs/bower/bower_components/dropzone/dist/min/dropzone.min.js There is a timeout of 30000 milliseconds (30 seconds)

Adaptation probably difficult because a patch in ILIAS itself is needed. Therefore, I will create an issue to bring something like the old chunk size configuration option back.

**Comment by chfsx** [comment]
The problem with the default 30 seconds is also in the core meanwhile a topic, this will be fixed with this PR then resp. there is then the possibility to adjust the value: https://github.com/ILIAS-eLearning/ILIAS/pull/6327

but the chunk size as a ticket is still being pursued: #193

**Comment by chfsx** [comment]
A fix is available in #205

**Comment by chfsx** [comment]
I reopen this since the PR #205 has not yet been merged

**Comment by dagraf** [comment]
As the PR https://github.com/opencast-ilias/OpenCast/pull/205 works as expected, got merged and enables to configure chunk sizes and therefore allows to support slower internet connection (if one wishes to do so) I close this ticket.
