### ISSUE TITLE
no mp4 files in the player with `sign player link` active if they are not signed by opencast

### ISSUE THREAD

**Issue by reiferschris** [opencast-ilias/OpenCast#183]
**Describe the bug**
If the option in the plugin Settings > Security > Sign Player Link is active the plugin also tries to sign mp4-files in the `PlayerDataBuilder`. This leads to not loading any mp4-files into the player script if opencast isn't configured to also sign mp4-files.

**To Reproduce**
1. Go to Settings > Security > Sign Player Link and activate it
2. Have opencast sign for example streaming URLs but not mp4-files (two different configs in opencast)
3. Play a video that also has mp4-files published or configure paella to prefer mp4 over hls
4. See that the player can't play the video (script in player page has no mp4 sources)

**Expected behavior**
The player should play mp4 files if they are published

**Log**
(https://github.com/opencast-ilias/OpenCast/commit/663f7c213bfb7cbc9f1196729137023678f5ffd6#diff-891b577fa4bbe49f62b56af7bdde8b3779510a3ec6b04e7315e336a74a8aacfbR104) Uses sign player link option to fetch mp4s

**Environment (please complete the following information):**
 - ILIAS version: [7.23]
 - PHP version: [PHP 7.4.33 ]
 - Plugin version: [5.1.1. and prior from this commit https://github.com/opencast-ilias/OpenCast/commit/663f7c213bfb7cbc9f1196729137023678f5ffd6#diff-891b577fa4bbe49f62b56af7bdde8b3779510a3ec6b04e7315e336a74a8aacfbR104 ]
 - Opencast version [doesn't matter]
 - Browser: [doesn't matter]

**Additional context**
The paella player can be configured to prefer HLS over mp4, in this case mp4s are rarely used but can aid as a fallback in case something is wrong with HLS (e.g. missing/broken publication)
The current option `Sign Player Link` assumes that all the assets in Opencast are handled the same which is often not the case.

**Suggested Solution**

- [x] Add a new config option for signing mp4 files which can be activated if opencast is configured to sign mp4s. This setting would then be used to check if the URL needs to be/ can be signed by opencast
- [ ] Add mention to the changelog

**Comment by ferishili** [comment]
Hi @reiferschris,
That should only cover `.mp4` files, or should we also include thumbnails `.jpg` files?

**Comment by reiferschris** [comment]
Thumbnails already have their own config option for that: `Sign Thumbnail Link` which I hope is already respected :)
