### ISSUE TITLE
ErrorException thrown with message "Class srag\DIC\OpenCast\Database\DatabaseDetector

### ISSUE THREAD

**Issue by reiferschris** [opencast-ilias/OpenCast#187]
Hi @mjansenDatabay
in which version of the plugin did this error occur for you? Also which version or better commit of ilias itself did you use?

sorry, maybe I was wrong. A colleague of mine sent me the following error ...

```bash
root@octa04-vm01:/srv/www/my.ilias.de/admin/ilias_errors# cat 83f24_1477.log
Whoops\Exception\ErrorException thrown with message "Class srag\DIC\OpenCast\Database\DatabaseDetector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (ilDBInterface::primaryExistsByFields)"

Stacktrace:
#2 Whoops\Exception\ErrorException in /srv/www/my.ilias.de/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/vendor/srag/dic/src/Database/DatabaseDetector.php:19
#1 Whoops\Run:handleError in /srv/www/my.ilias.de/ilias/libs/composer/vendor/filp/whoops/src/Whoops/Run.php:514
#0 Whoops\Run:handleShutdown in [internal]:0


-- GET Data --

ref_id                   : 31
admin_mode               : settings
ctype                    : Services
cname                    : Repository
slot_id                  : robj
pname                    : OpenCast
cmd                      : refreshLanguages
cmdClass                 : ilobjcomponentsettingsgui
cmdNode                  : 1d:m0
baseClass                : ilAdministrationGUI
```

... and pointed me to THIS issue here. Bug maybe this is a different problem. If yes, please ignore my comment.

_Originally posted by @mjansenDatabay in https://github.com/opencast-ilias/OpenCast/issues/169#issuecomment-1688644855_

**Comment by tmuellerdatabay** [comment]
I updated ILIAS Core and roll out the plugin yesterday afternoon fresh from repository.
Everything is up to date as well.
It is possible that improvements to ILIAS have led to incompatibility.

To reproduce it, you would have to check out both fresh.
I suspect that pure updates (minor version jumps) are not affected.

**Comment by tmuellerdatabay** [comment]
ILIAS:
* release_7                3618457016 Merge pull request #6256 from Minervis-GmbH/_7/soap/group/container_settings

Plugin:
* main                                                                 bc9b2a1e Added Readme for Branching and Versioning

**Comment by reiferschris** [comment]
Thank you for the details. Unfortunately we (Uni Köln) are also affected even with the old version of the plugin (not the community version).
Our test system also has this error when updating it to the current main branch.

**Comment by ferishili** [comment]
I can confirm that PR #186 (i.e. removing DICTrait) solve this problem, therefore, this issue has to be linked with that PR!
