### ISSUE TITLE
Only with PR186: Course member do not see column "Presenter"

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#188]
**Describe the bug**
In tab "Content": Course members (or more in general: users without the right "Edit videos") do not see the column "Presenter". It also does NOT get offered when hitting on "Columns" and when activating the filter it is also not offered.

**To Reproduce**
1. Be logged in as a users that has NOT the right "Edit videos"
2. Got to tab "Content"
3. Switch the filter to "On"
4. Click on "column"
5. See errors: (i) the column "Presenter" is missing in the table (should be shown by default), (ii) there is no filter option for "Presenter, (iii) the information "Presenter" can not be selected to get shown in the table

**Expected behavior**
The column "Presenter" should be shown also to users who do not have the right "edit videos" and they should be possible to filter for it and to (de-)activate it.

**Screenshots**
Left: User WITH right "Edit videos"; Right: User WITHOUT right "Edit videos"

<img width="2533" alt="Bildschirmfoto 2023-08-24 um 10 47 54" src="https://github.com/opencast-ilias/OpenCast/assets/15246287/24d39898-2e39-4783-afba-24166bc2d3f3">

**Environment (please complete the following information):**
 - ILIAS version: v7.24 2023-07-20
 - Plugin version: 5.1.1 with https://github.com/opencast-ilias/OpenCast/pull/186#issuecomment-1689976723 (state: 24.8.2023)
 - Opencast version: 12
 - Browser: Firefox

**Additional context**
Only when with https://github.com/opencast-ilias/OpenCast/pull/186# (state: 24.8.2023)

**Comment by ferishili** [comment]
Hi @dagraf
the first thing came to mind is that, it is perhaps due to the visibility config (called `Visible for`) of that metadata item (which should be set to `admin only`), please double-check that option and set it to everyone.

![Screenshot 2023-08-24 at 13 14 50](https://github.com/opencast-ilias/OpenCast/assets/53179227/47829c61-c979-4462-8832-d0e8a6504b5a)

**Comment by dagraf** [comment]
Thanks for the hint. You were right. The visibility was set to "Only admins". Now it works as expected. Sorry for the unnecessary bug report.

Therefore, I close this issue.
