### ISSUE TITLE
Only with PR186: Reporting of "Quality Problems" and "Date Modifications" do not work

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#189]
**Describe the bug**
When clicking on "Send" in the modals "Report Quality Problems" and "Report Date Modifications" the button "Send" gets deactivated/greyed out but nothing happens

**To Reproduce**
1. In the config: Enable the options "Report Quality Problems" and "Report Date Modifications"
2. Click on "Report Date Modifications" or "Report Date Modifications"
3. Enter a text and hit on "Send"
4. See that nothing happens: Modal remains open

**Expected behavior**
After clicking on "Send" the modal should get closed and a corresponding message shown (i.e., "Die Meldung wurde abgeschickt. Der Support wurde benachrichtigt und meldet sich bei Ihnen.")

**Screenshots**
<img width="654" alt="Bildschirmfoto 2023-08-24 um 21 16 06" src="https://github.com/opencast-ilias/OpenCast/assets/15246287/62125036-2e6c-4c94-858b-74880d1e3ab7">
<img width="654" alt="Bildschirmfoto 2023-08-24 um 21 16 06" src="https://github.com/opencast-ilias/OpenCast/assets/15246287/32cd5011-0124-42e3-b43f-5b32b125c86e">

**Environment (please complete the following information):**
- ILIAS version: v7.24 2023-07-20
- Plugin version: 5.1.1 with https://github.com/opencast-ilias/OpenCast/pull/186#issuecomment-1689976723 (state: 24.8.2023)
- Opencast version: 12
- Browser: Firefox

**Additional context**
Only when with https://github.com/opencast-ilias/OpenCast/pull/186 (state: 24.8.2023)

**Comment by ferishili** [comment]
Fixed in https://github.com/opencast-ilias/OpenCast/pull/186/commits/0cf065f49d37d6ffb7996749e5cec6cfb0d28c29 under #186

**Comment by ferishili** [comment]
Please re-check and close this issue if that problem is solved!

**Comment by dagraf** [comment]
After pulling the fix https://github.com/opencast-ilias/OpenCast/commit/0cf065f49d37d6ffb7996749e5cec6cfb0d28c29 under https://github.com/opencast-ilias/OpenCast/pull/186 it works as expected. I therefore close this issue.
