### ISSUE TITLE
Only with PR186: Workflows do not get started

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#190]
**Describe the bug**
In the the modal "Start workflow" (opened by clicking on "Actions" > "Start worklow") a click on "Save" shows no effect. The button gets deactivated/greyed out and nothing happens.

**To Reproduce**
1. In the config: Have some Workflows configured
2. In the tab "Content": Click on "Actions" > "Start worklow"
3. In the modal "Start workflow": Choose a workflow and cklick on "Save"
4. See error: Nothing happens

**Expected behavior**
Modal should get closed, a message should appear (i.e. "Workflow erfolgreich gestartet.") and the selected workflow should get started in Opencast.

**Screenshots**
<img width="621" alt="Bildschirmfoto 2023-08-24 um 21 23 54" src="https://github.com/opencast-ilias/OpenCast/assets/15246287/a3455c9d-a634-40c2-8d9f-f146a4de2443">

**Environment (please complete the following information):**
- ILIAS version: v7.24 2023-07-20
- Plugin version: 5.1.1 with https://github.com/opencast-ilias/OpenCast/pull/186#issuecomment-1689976723 (state: 24.8.2023)
- Opencast version: 12
- Browser: Firefox

**Additional context**
- Only when with https://github.com/opencast-ilias/OpenCast/pull/186 (state: 24.8.2023)
- This issue could be related to issue https://github.com/opencast-ilias/OpenCast/issues/189

**Comment by ferishili** [comment]
Fixed in https://github.com/opencast-ilias/OpenCast/pull/186/commits/0cf065f49d37d6ffb7996749e5cec6cfb0d28c29 under #186

**Comment by ferishili** [comment]
Please re-check and close this issue if that problem is solved!

**Comment by dagraf** [comment]
After pulling the fix https://github.com/opencast-ilias/OpenCast/commit/0cf065f49d37d6ffb7996749e5cec6cfb0d28c29 under https://github.com/opencast-ilias/OpenCast/pull/186 it works as expected. I therefore close this issue.
