### ISSUE TITLE
Make chunk size configurable again

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#193]
**Is your feature request related to a problem? Please describe.**
In the old version of the plugin, it was possible to configure the chunk size of the chunk upload. Momentarily, this chunk size is hard coded to 20MB. With slow upload speed, this leads to uploads getting stuck (see https://github.com/opencast-ilias/OpenCast/issues/176). 

**Describe the solution you'd like**
In order to improve the flexibility of the plugin please bring back some sort of option to configure the chunk size. As default please set a chunk size of 20MB.

**Describe alternatives you've considered**

- The timeout that leads to the abortion of an upload after 30 seconds is set in libs/bower/bower_components/dropzone/dist/min/dropzone.min.js There is a timeout of 30000 milliseconds (30 seconds). Adaptation of this value is pretty difficult because a patch in ILIAS itself would be needed.
- Lowering the hard coded chunk size would solve the issue described here (https://github.com/opencast-ilias/OpenCast/issues/176) but would make the upload slower in general.

**Additional context**
This feature was discussed at the community meeting on 5.9.2023.

**Comment by dagraf** [comment]
@chfsx Da in diesem Zusammenhang wiederholt Nachrichten auf der OC-LMS Liste eintreffen: Kannst du bitte dieses Feature in den nächsten zwei Wochen angehen? Danke.

**Comment by chfsx** [comment]
Das Feature wurde nun in #205 implementiert

**Comment by dagraf** [comment]
As PR https://github.com/opencast-ilias/OpenCast/pull/205 works as expected and got merged, I close this ticket.
