### ISSUE TITLE
Default workflow parameters are ignored when a parameter uses form-based configuration

### ISSUE THREAD

**Issue by Hufschmidt** [opencast-ilias/OpenCast#209]
**Describe the bug**
When you have configured workflow parameters with a mix of '_Always Active_' (_Immer Aktiv_) and '_Show in Form_' (_Im Formular anbieten_) or '_Show in Form (checkbox selected)_' (_Im Formular anbieten (Checkbox ausgewählt)_) then during shedule/upload of a new event/video all default values are ignored and only '_Show in Form_' and ''_Show in Form (checkbox selected)_' workflow parameters are set

**To Reproduce**
This is just one of many possible examples:
- Make sure the plugin is installed and configured to work properly with ILIAS and OpenCast
- Use (slightly customized) '_schedule-and-upload_' as Processing-Workflow-ID
  - For sake of simplicity lets asume this workflow is still configured with multiple workflow parameters as for example in OpenCast [10.4](https://github.com/opencast/opencast/blob/10.14/etc/workflows/schedule-and-upload.xml)
  - Note: We arer using a one that is similar to this (see **Additional context**), but with OpenCast 14.5
  - Optional: Change opencast workflow defaults to **false** for `publishToEngage` and `publishToApi`
- Load parameters via API
- Configure the resolution related workflow parameter checkboxes to be able to be set via form
  - For example all `flagQuality*p` parameters set to '_Show in Form (checkbox selected)_'
- Configure `holdOrPublishToggle_publish` and `publishToApi` workflow parameters to be configured as '_Always Active_'
- Create a new OpenCast Series/Object in ILIAS
- Upload new event for newly created OpenCast Series/Object in ILIAS
- Open the OpenCast AdminUI after the Event has been uploaded
- Open the Events Metadata -> Workflows -> Process upon upload and schedule > Details and investigate the given workflow parameters

You should notice that parameters set via the upload form can be changed depending on your input, but any parameter that should be enabled by default is not applied, like in our example `publishToApi`.

**Expected behavior**
If a workflow parameter is set to be _'Always Active'_ one would expect that this parameter is always passed as **true** to the default Processing-Workflow. At least that is how it works when no workflow parameter is configured to be form-based and I'm sure that this is how it worked in the old fluxlabs version of the plugin as well.

**Screenshots**
Example workflow parameter configuration:
![277665535-d1764df5-4a13-404c-90f7-4eea6786f66a](https://github.com/opencast-ilias/OpenCast/assets/11391961/c0f6e9f5-cad7-4793-83c1-83dc169acb4f)
(_Compare with workflow definition in **Additional context**_)

**Environment (please complete the following information):**
 - ILIAS version: 7.26
 - PHP version: 7.4
 - Plugin version: 5.2.0 (_44ac530093a998b525b0a73ba536e64f03bbaff47446cf99e1a31d6a042a4549_)
 - Opencast version 14.5
 - Browser: Any

**Additional context**
- Our workflows: [Workflows.zip](https://github.com/opencast-ilias/OpenCast/files/13164188/Workflows.zip)
  - Note that we've disabled all publications by default when this workflow is used from within OpenCast
  - When it is used from within ILIAS we'd like to instead allow 'publishToCms' to be configured via form (as it is optional) and always enable 'publishToIlias'.
  - We could create a custom workflow in OpenCast for ILIAS that sets this variable to true by default as a Workaround, but fixing this seems like the better solution as otherwise there wouldn't be any reason to allow Workflow-Parameters to be set to anything but form-based control in the plugin itself...

**Comment by Amstutz** [comment]
thx for the report and the PR.
