### ISSUE TITLE
Upload of larger Video-Files (500MB+) throws an exception

### ISSUE THREAD

**Issue by marcusm7** [opencast-ilias/OpenCast#220]
**Describe the bug**
Uploading of larger video files fails with an exception (Allowed memory size of ... bytes exhausted).

**To Reproduce**
1. Set the plugin-property "Maximale Upload-Größe in MB" to 12288 and "Chunk-Größe in MB" to 20
2. Click on 'Aufzeichnung hochladen' (Upload), 
3. Select a 2gb video and wait until the upload is done
4. Enter arbitrary metadata (title, description,...)
5. Click on 'Speichern' (save)

**Expected behavior**
The plugin should process uploads of all video sizes which are allowed by the given plugin-settings (i.e. 200MB, 500MB, 2GB, 10GB sized videos).

**Screenshots**
![grafik](https://github.com/opencast-ilias/OpenCast/assets/77965251/ada35c07-35d6-4546-8a20-f71aa27f091f)
![grafik](https://github.com/opencast-ilias/OpenCast/assets/77965251/0031f37b-f3ed-419b-a876-831a909d5198)

**Log**
Whoops\Exception\ErrorException thrown with message "Allowed memory size of 2621440000 bytes exhausted (tried to allocate 1608515616 bytes)"

Stacktrace:
#2 Whoops\Exception\ErrorException in /.../ilias/libs/composer/vendor/guzzlehttp/psr7/src/Utils.php:94
#1 Whoops\Run:handleError in /.../ilias/libs/composer/vendor/filp/whoops/src/Whoops/Run.php:514
#0 Whoops\Run:handleShutdown in [internal]:0

**Environment (please complete the following information):**
 - ILIAS version:  ILIAS (v7.26 2023-10-23)
 - PHP version: 7.4.3-4ubuntu2.19 + Ilias-Workers: php7.4-fpm 7.4.3-4ubuntu2.19
 - Plugin version: 5.3.1
 - Opencast version: Opencast 14.4.0 - f7999ce - built on 2023-10-31 
 - Browser: Firefox 119.0.1 (64-Bit)

**Additional context**
Smaller videos (200MB) work fine.

**Comment by chfsx** [comment]
@ferishili and me discussed this last week already and will look for a solutions asap

**Comment by marcusm7** [comment]
I just tried the fix (https://github.com/opencast-ilias/OpenCast/pull/221), the upload of very large files works now. Thanks!

![grafik](https://github.com/opencast-ilias/OpenCast/assets/77965251/c20c9e51-b228-4f1a-b3ff-93ce50fc8b15)

**Comment by dagraf** [comment]
Since this PR got fixed with the now merged PR https://github.com/opencast-ilias/OpenCast/pull/221#event-11022425368 I close this issue.
