### ISSUE TITLE
Grant access rights: Thumbnail appears to big

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#23]
**Error description**

When an admin wants to give a user acces rights to a video (precondition: setting "Set permissions for an Event" has to be activated"), the thumbnail of the video appearing in the form to give this access rights is way to big (see screenshot). 
<img width="2024" alt="Bildschirmfoto 2022-04-26 um 17 27 07" src="https://user-images.githubusercontent.com/15246287/165337314-51054eb6-9b24-48dd-88fd-2ef844ddb55d.png">

**Desired solution**

Please resize the thumbnail. A possibility would be to use the same size as in den "Edit Owner" form (see screenshot).
<img width="2018" alt="Bildschirmfoto 2022-04-26 um 17 27 42" src="https://user-images.githubusercontent.com/15246287/165337561-d697409c-02f5-4ae3-a3c8-04d9747072e4.png">

**Comment by Amstutz** [comment]
Hi @dagraf 

@okaufman implemented a solution for this issue, which has been merged. I close this, however, can you do a short re-test, to make sure that this issue has been resolved?

Thx.

**Comment by dagraf** [comment]
I did a re-test. Issue is solved, thx!
