### ISSUE TITLE
504 Gateway Time-out message after large size video upload

### ISSUE THREAD

**Issue by ralede** [opencast-ilias/OpenCast#233]
when I upload a large video file (3,9 GB), the message "504 Gateway Time-out" appears, although the video is then processed by opencast without any problems

**To Reproduce**
1. create a new or exising opencast object/serie
2. click on "upload"
3. select a large size video
4. enter a title
5. click on "save"
6. after the rotating upoad bar (50 seconds...) it appers the message "504 Gateway Time-out"
7. the rendering process on opencast is still displayed, when you click back to the opencast object/serie

**Expected behavior**
no error message

**Log**
Nginx Log:
2023/11/27 14:06:17 [error] 7547#7547: *1617 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 131.220.19.28, server: [ilias-test.hrz.uni-bonn.de](http://ilias-test.hrz.uni-bonn.de/), request: "POST /ilias.php?ref_id=8688&cmd=post&cmdClass=xocteventgui&cmdNode=qp:qh:19b&baseClass=ilobjplugindispatchgui&fallbackCmd=create&rtoken=2144ea7d6fa839f493b48524ee89d668 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock", host: "[ilias-test.hrz.uni-bonn.de](http://ilias-test.hrz.uni-bonn.de/)", referrer: "https://ilias-test.hrz.uni-bonn.de/ilias.php?ref_id=8688&cmd=add&cmdClass=xocteventgui&cmdNode=qp:qh:19b&baseClass=ilobjplugindispatchgui".

**Environment (please complete the following information):**
ILIAS 7.26 2023-10-23
Opencast Plugin 5.6.0
nginx/1.18.0
PHP 7.4.33 (FPM)
max_execution_time 10.800
max_input_time 3.600

**Comment by dagraf** [comment]
@ralede: This issue was created quite some time ago. Does it still exist?

**Comment by ralede** [comment]
This error no longer occurs in Release 7 :-)
Ilias 7.29
Opencast PlugIn 7.02
