### ISSUE TITLE
Adaptive HLS streaming not working properly in Paella Player 7

### ISSUE THREAD

**Issue by snoesberger** [opencast-ilias/OpenCast#239]
**Describe the bug**
When playing a video that has been prepared as Adaptive HLS, the Paella Player will only play a single video resolution. It does not automatically switch between the different video resolutions according to the available network bandwidth, nor can it be done manually by the user. The master playlist will be ignored by the player and only one of the variant playlists will be loaded.

**To Reproduce**
1. Within Opencast setup an adaptive HLS encoding profile and workflow. Encode a video with this adaptive HLS encoding profile
2. Play the adaptive HLS video in ILIAS
3. Check in the "gear" -> "video quality" menu of the Paella player the available resolutions: only the options "auto" and "0x" are available
4. limiting the network bandwidth in the browser console will not force the player to switch to a smaller resolution.

**Expected behavior**
In the "gear" -> "video quality" menu of the Paella player every available video resolution should be visible.

**Environment (please complete the following information):**
 - ILIAS version: 8.0
 - Plugin version: 8.0
 - Opencast version 14
 - Paella 7

**Additional context**
@ferishili has already a solution for this problem: https://github.com/opencast-ilias/OpenCast/compare/main...elan-ev:ilias-opencast-plugin:bern-master-playlist

**Comment by dagraf** [comment]
Fixed in release_7 and release_8.
