### ISSUE TITLE
no return to new object when creating new series, stuck with loading

### ISSUE THREAD

**Issue by reiferschris** [opencast-ilias/OpenCast#24]
In ILIAS 7.7 on the current `main`-Branch (v.4.0.1) the creation of a new series within Opencast succeeds, but the plugin does not return to the newly created opencast object within ILIAS. 

Does not work:
Environment information: FF 97, Linux, PHP 7.4.29, ILIAS 7.9 (27.04.2022), Plugin v.4.0.1

does work:
Environment information: FF 97, Linux, PHP 7.4.3, ILIAS 6.15 (22.02.2022), Plugin v.4.0.1

![cant-exit-create-series-dialoque-1](https://user-images.githubusercontent.com/34450887/165734134-9dd319bc-5187-41c6-aec9-e0a2016f01b4.png)

**Comment by reiferschris** [comment]
I looked into this issue a little further and found that the URL contained `async=true` and that URL returned `404`.  I might have missed this additional parameter previously but disabling asynchronous loading of the events in the advanced section of the plugin fixed the issue for me. We also do not have caching enabled at least in our test-environments, there might be a link between those two configuration options?

**with** async the URL is not reachable
```
ref_id=90
cmdClass=xocteventgui
cmdNode=p2:ou:177
baseClass=ilObjPluginDispatchGUI
async=true
```

**without** async it works
```
ref_id=99
cmdClass=xocteventgui
cmdNode=p2:ou:177
baseClass=ilObjPluginDispatchGUI
```

**Comment by ferishili** [comment]
Hi @reiferschris,
I could not reproduce this issue in both ILIAS versions 6&7.
Could you please rerun/retest this issue and check if this problem is still there?

**Comment by reiferschris** [comment]
Hi @ferishili 
I still encounter this issue in our ilias7 test system if the option to load the event table synchronously is not set. It could very well be an issue with the settings in nginx, I'll check again if I find something suspicious. Maybe someone else who runs ILIAS 7 can check if they also see this issue.

**Comment by reiferschris** [comment]
Seems like this issue is caused by something in our proxy configuration and no one else is affected.
