### ISSUE TITLE
CORS issue prevents internal Paella 7 player from playing video (progressive streaming) and solution

### ISSUE THREAD

**Issue by DZenker** [opencast-ilias/OpenCast#243]
**Describe the bug**
After installing the current plugin version with Paella 7 player, I realized that the Paella 7 player could not load video files from Opencast and play them due to a CORS issue (inadequate "allow-cross-origin" header setting).

**To Reproduce**
1. Click on video preview
2. Paella 7 player opens in new tab/window
3. Press play
4. Error message that video could not be loaded

**Expected behavior**
Video should load and play

**Environment (please complete the following information):**
 - ILIAS version: 7.27
 - PHP version: 7.4
 - Plugin version: 5.6.0
 - Opencast version 14.8
 - Browser: all

**Solution**
The problem can be solved by adding a crossorigin attribute in the player config.json, e.g. for progressive download:
_...
    "es.upv.paella.mp4VideoFormat": {
      "enabled": true,
      "order": 1,
      **"crossOrigin": false**
      },
..._

My suggestion is to integrate this option into the config.json by default.

**Comment by mic-men** [comment]
I can confirm the problem and the proposed solution.
- ILIAS version: 7.30
- PHP version: 7.4
- Plugin version: 7.0.3 (May 2024)
- Opencast version 14.6

I'm not sure if necessary but applied the additional flag to
- es.upv.paella.mp4VideoFormat
- es.upv.paella.htmlVideoFormat
- es.upv.paella.imageVideoFormat
- es.upv.paella.audioVideoFormat

I foster the proposed integration into config.son.

**Comment by DZenker** [comment]
Although the problem can be solved with the above setting, it is recommended to solve this via a suitable directive in the web server config. One of the reasons for this is that it also enables the loading of subtitle files (*.vtt), for example, which cannot be configured in the player config.

Example for the Nginx Config:
        _add_header Access-Control-Allow-Origin “opencast.my-university.de”;
        add_header Access-Control-Allow-Origin “ilias.my-university.de”;_

**Important:** this directive must be configured on the source AND target system, i.e. on both the ILIAS server and the Opencast Presentation Node!
