### ISSUE TITLE
Release_8: Workflow description do not get shown

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#244]
**Describe the bug**
When an admin wants to start a workflow (Actions > Start Workflow > Select a workflow) the configured description or configuration panels do not get shown. This bug does only appear when the config option "Load event table synchronously" is activated. If it is deactivated, the descriptions get shown. So for now, it would be a workaround to deactivate this config option.
In the console, when the config option "Load event table synchronously" is activated the error "Uncaught ReferenceError: $ is not defined" appears each time a user loads the tab "Content".

**To Reproduce**
1. Have some workflows with descriptions or configuration panels configured
2. Click on 'Action' > 'Start workflow'
3. Select a workflow

**Expected behavior**
When a workflow gets selected in the modal 'Start Workflow' its description or configuration panel should be shown.

**Screenshots**
![Workflow Description Bug](https://github.com/opencast-ilias/OpenCast/assets/15246287/7262ef96-ed34-442e-875c-e3b596fadf2b)

<img width="1203" alt="Bildschirmfoto 2024-02-26 um 10 37 12" src="https://github.com/opencast-ilias/OpenCast/assets/15246287/51e7688d-0c55-4cdd-a8f4-30a9320cfaaf">

**Environment (please complete the following information):**
 - ILIAS version: v8.7 2023-11-28
 - Plugin version: 8.0.0
 - Opencast version: 14
 - Browser: Firefox

**Additional context**
The bug does not exist in release_7.

**Comment by chfsx** [comment]
There are now two PRs to fix this issue in ILIAS 8 (#246), the PR #245 has the same commits for ILIAS 7 for consistency reasons

**Comment by chfsx** [comment]
Resolved in version 7.0.1 and 8.0.1
