### ISSUE TITLE
Release_7: chunk size is limited to 1 MB only

### ISSUE THREAD

**Issue by DZenker** [opencast-ilias/OpenCast#248]
**Describe the bug**
I've just upgraded from V. 5.6 to the current 7.0.1 for ILIAS 7: I have discovered that in the configuration for the upload chunk size the input is restricted to 1 MB , as the min and max values of this field are identical and equal 1.

**To Reproduce**
1. Go to "Settings - Events" section of the plugin
2. Click on 'Chunk size in MB" 
3. Enter a value different to 1 and click on "update" button
4. Error message appears: "Some data is incomplete or not valid. Please correct the form input."

**Expected behavior**
Input values in a range of, for instance, 1-100 should be possible.

**Screenshots**
[Community Version 7 0 1 - only 1 MB setting for chunk size](https://github.com/opencast-ilias/OpenCast/assets/5229751/e2de7a66-850e-4b2d-a2d2-fe1841c0840d)

**Environment (please complete the following information):**
 - ILIAS version: 7.28
 - PHP version: 7.4.3
 - Plugin version: 7.0.1
 - Opencast version 14.8
 - Browser: any

**Additional context**
**Furthermore, no upload progress bar is shown during upload of the video** - may be this is related to this issue, e.g. it cannot be calculated and rendered if the chunk size is 1 MB only.

![Community Version 7 0 1 - only 1 MB setting for chunk size](https://github.com/opencast-ilias/OpenCast/assets/5229751/e2de7a66-850e-4b2d-a2d2-fe1841c0840d)

**Comment by dagraf** [comment]
This bug appears also on our installation. @chfsx: Can you have a look at it? Thx.

**Comment by chfsx** [comment]
There is a proposed fix in #260

**Comment by dagraf** [comment]
@DZenker: Can you test this PR in the following days?

**Comment by chfsx** [comment]
The PR has been merged, see #260. I therefore close the issue

**Comment by dagraf** [comment]
@chfsx This bug appears now also on the v8.1.4 release. Could you please fix it as soon as possible? Thx!

**Comment by dagraf** [comment]
Update: On our ILIAS test platform we had the problem that 1 was specified as the maximum chunk size. However, we had post_max_size=8M and upload_max_filesize=2M in php.ini. Now we have raised the upload_max_filesize to 8M. Now 4 appears as the maximum value. 

Therefore I close the ticket.
