### ISSUE TITLE
release_7: Unable to import new settings

### ISSUE THREAD

**Issue by reiferschris** [opencast-ilias/OpenCast#249]
**Describe the bug**
Upon trying to import settings generated from version 5.6 you get this message `Unable to import new settings`

 but no _error_
The main settings (API etc) are imported but publications, metadata are missing 

**To Reproduce**
1. Create an export from an older version (5.6.) (or use the provided export and strip the `.txt` because github doesn't allow uploading `.xml` [opencastexport_v5.6-sanitized.xml.txt](https://github.com/opencast-ilias/OpenCast/files/14445268/opencastexport_v5.6-sanitized.xml.txt))
2. Import it in the settings tab import/export
3. See error and incomplete settings in the tabs (e.g. Publications, Metadata)

**Expected behavior**
Settings are imported fully

**Log**
No error log created

**Environment (please complete the following information):**
 - ILIAS version: [v7.25]
 - PHP version: [PHP 7.4.33]
 - Plugin version: [release_7 commit 94366ce49e626e9c94e3343b3ed1629c15d2f512]
 - Opencast version [ 13.x]
 - Browser: [FF]

**Additional context**

**Comment by dagraf** [comment]
After deploying https://github.com/opencast-ilias/OpenCast/pull/258, the error no longer appears (tested by @reiferschris). Therefore, I close this issue.
