### ISSUE TITLE
release_7: Can't create export from settings

### ISSUE THREAD

**Issue by reiferschris** [opencast-ilias/OpenCast#250]
**Describe the bug**
When trying to create an export file in the settings an error is encountered

**To Reproduce**
1. Go to plugin settings -> Import/Export
2. Click on Export Settings

**Expected behavior**
An export file is created

**Log**
```
TypeError thrown with message "DOMElement::__construct() expects parameter 2 to be string, int given"

Stacktrace:
#15 TypeError in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/Config/PluginConfig.php:421
#14 DOMElement:__construct in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/Config/PluginConfig.php:421
#13 srag\Plugins\Opencast\Model\Config\PluginConfig:getXMLExport in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Conf/Export/class.xoctConfExportGUI.php:66
#12 xoctConfExportGUI:export in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:74
#11 xoctGUI:performCommand in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:68
#10 xoctGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#9 ilCtrl:forwardCommand in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctMainGUI.php:120
#8 xoctMainGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#7 ilCtrl:forwardCommand in /var/www/html/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilOpenCastConfigGUI.php:75
#6 ilOpenCastConfigGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#5 ilCtrl:forwardCommand in /var/www/html/Services/Component/classes/class.ilObjComponentSettingsGUI.php:113
#4 ilObjComponentSettingsGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#3 ilCtrl:forwardCommand in /var/www/html/Services/Administration/classes/class.ilAdministrationGUI.php:246
#2 ilAdministrationGUI:executeCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:217
#1 ilCtrl:forwardCommand in /var/www/html/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /var/www/html/ilias.php:23
```

**Environment (please complete the following information):**
- ILIAS version: [v7.25]
- PHP version: [PHP 7.4.33]
- Plugin version: [release_7 commit https://github.com/opencast-ilias/OpenCast/commit/94366ce49e626e9c94e3343b3ed1629c15d2f512]
- Opencast version [ 13.x]
- Browser: [FF]

**Additional context**
Maybe related to https://github.com/opencast-ilias/OpenCast/issues/249 ?

**Comment by FraenzePacita** [comment]
Same problem with release_8

Environment:

- ILIAS version: [v8.9]
- PHP version: [PHP 8.0]
- Plugin version: [release_7 commit https://github.com/opencast-ilias/OpenCast/commit/94366ce49e626e9c94e3343b3ed1629c15d2f512](https://github.com/opencast-ilias/OpenCast/commit/72c4cb5b714bde9ac71eda0fe76efea7405d87fb)]
- Opencast version [ 13.x und 14x]
- Browser: [FF]

Log

`Error thrown with message "Call to undefined method ilOpenCastPlugin::getDBVersion()"

Stacktrace:
#15 Error in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/Config/PluginConfig.php:421
#14 srag\Plugins\Opencast\Model\Config\PluginConfig:getXMLExport in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Conf/Export/class.xoctConfExportGUI.php:66
#13 xoctConfExportGUI:export in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:74
#12 xoctGUI:performCommand in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:68
#11 xoctGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#10 ilCtrl:forwardCommand in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctMainGUI.php:120
#9 xoctMainGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#8 ilCtrl:forwardCommand in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilOpenCastConfigGUI.php:75
#7 ilOpenCastConfigGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#6 ilCtrl:forwardCommand in /srv/ilias/ilias/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php:162
#5 ilObjComponentSettingsGUI:forwardConfigGUI in /srv/ilias/ilias/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php:119
#4 ilObjComponentSettingsGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#3 ilCtrl:forwardCommand in /srv/ilias/ilias/Services/Administration/classes/class.ilAdministrationGUI.php:237
#2 ilAdministrationGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#1 ilCtrl:forwardCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:174
#0 ilCtrl:callBaseClass in /srv/ilias/ilias/ilias.php:24
`

**Comment by dagraf** [comment]
This bug appears also on our installation. @chfsx: Can you have a look at it? Thx.

**Comment by dagraf** [comment]
After deploying https://github.com/opencast-ilias/OpenCast/pull/258, the error no longer appears (tested by @reiferschris). Therefore, I close this issue.
