### ISSUE TITLE
Error when deleting workflow parameters

### ISSUE THREAD

**Issue by FraenzePacita** [opencast-ilias/OpenCast#251]
**Describe the bug**
when I try to delete a workflow parameter an error code is thrown

**To Reproduce**
1. Go to plugin settings -> Workflow Parameter
2. Select a workflow parameter -> Click on ''Actions" -> "Delete"

**Expected behavior**
the workflow parameter is deleted

**Log**
TypeError thrown with message "ilConfirmationGUI::addItem(): Argument #2 ($a_id) must be of type string, int given, called in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Conf/WorkflowParameters/class.xoctWorkflowParameterGUI.php on line 315"

Stacktrace:
#15 TypeError in /srv/ilias/ilias/Services/UIComponent/Confirmation/class.ilConfirmationGUI.php:107
#14 ilConfirmationGUI:addItem in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Conf/WorkflowParameters/class.xoctWorkflowParameterGUI.php:315
#13 xoctWorkflowParameterGUI:delete in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Conf/WorkflowParameters/class.xoctWorkflowParameterGUI.php:114
#12 xoctWorkflowParameterGUI:performCommand in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:68
#11 xoctGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#10 ilCtrl:forwardCommand in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctMainGUI.php:139
#9 xoctMainGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#8 ilCtrl:forwardCommand in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilOpenCastConfigGUI.php:75
#7 ilOpenCastConfigGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#6 ilCtrl:forwardCommand in /srv/ilias/ilias/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php:162
#5 ilObjComponentSettingsGUI:forwardConfigGUI in /srv/ilias/ilias/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php:119
#4 ilObjComponentSettingsGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#3 ilCtrl:forwardCommand in /srv/ilias/ilias/Services/Administration/classes/class.ilAdministrationGUI.php:237
#2 ilAdministrationGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#1 ilCtrl:forwardCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:174
#0 ilCtrl:callBaseClass in /srv/ilias/ilias/ilias.php:24

**Environment (please complete the following information):**
 - ILIAS version: [v8.9]
 - PHP version: [PHP8.0]
 - Plugin version: [v8.0.1]
 - Opencast version [13x und 14x]
 - Browser: [FF]

**Comment by dagraf** [comment]
This bug appears also on our installation. @chfsx: Can you have a look at it? Thx.

**Comment by dagraf** [comment]
After deploying https://github.com/opencast-ilias/OpenCast/pull/255, the error no longer appears. Therefore, I close this issue.
