### ISSUE TITLE
Release 8: Metadata -> Series -> license (and language)

### ISSUE THREAD

**Issue by tkurze** [opencast-ilias/OpenCast#252]
**Describe the bug**
When trying to add the license metadata field, but also for the language field (probably for all fields that accept a list of possible values), en error is raised.

**To Reproduce**
1. Go to 'Plugin Configuration -> Metadata -> Series'
2. Click on 'New Metadata field -> Series'
3. Scroll down to 'possible values' and insert "CC: Attribution||| blabla attribution" for example. Fill in all the other fields and click save

**Expected behavior**
No error should be raised; meta data field should be added.

**Log**
Whoops\Exception\ErrorException thrown with message "Undefined array key "prefill""
 
Stacktrace:
#17 Whoops\Exception\ErrorException in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/Metadata/Config/Series/MDFieldConfigSeriesRepository.php:82
#16 ilErrorHandling:handlePreWhoops in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/Metadata/Config/Series/MDFieldConfigSeriesRepository.php:82
#15 srag\Plugins\Opencast\Model\Metadata\Config\Series\MDFieldConfigSeriesRepository:storeFromArray in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Conf/Metadata/class.xoctMetadataConfigGUI.php:307
#14 xoctMetadataConfigGUI:store in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Conf/Metadata/class.xoctMetadataConfigGUI.php:116
#13 xoctMetadataConfigGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#12 ilCtrl:forwardCommand in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Conf/Metadata/class.xoctMetadataConfigRouterGUI.php:54
#11 xoctMetadataConfigRouterGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#10 ilCtrl:forwardCommand in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctMainGUI.php:144
#9 xoctMainGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#8 ilCtrl:forwardCommand in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilOpenCastConfigGUI.php:75
#7 ilOpenCastConfigGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#6 ilCtrl:forwardCommand in /srv/ilias/ilias/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php:162
#5 ilObjComponentSettingsGUI:forwardConfigGUI in /srv/ilias/ilias/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php:119
#4 ilObjComponentSettingsGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#3 ilCtrl:forwardCommand in /srv/ilias/ilias/Services/Administration/classes/class.ilAdministrationGUI.php:237
#2 ilAdministrationGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#1 ilCtrl:forwardCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:174
#0 ilCtrl:callBaseClass in /srv/ilias/ilias/ilias.php:24
 

**Environment (please complete the following information):**
 - ILIAS version: 8.9
 - PHP version: 8.?
 - Plugin version: 8.0.1
 - Opencast version 14
 - Browser: chrome

**Comment by reiferschris** [comment]
Hi @tkurze 
Thanks for the bug report. I also encountered that problem and asked if someone else had this issue in our community chat https://matrix.to/#/#ilias-oc-plguin-community:matrix.org

This apparently happens when upgrading from a version prior to 5.6 . 

<details><summary>Here is what I found:</summary>
<p>

I can now recreate this behaviour though:
edit: the cherry pick is necessary because otherwise you cannot install/uninstall the plugin with those commits..

The first commit is https://github.com/opencast-ilias/OpenCast/commit/53b4e8bcf49cb713ac81afffd426a86d19b0f826 prior to dbupdate step `#45` The other cherry-picked commits are simply necessary because they solve a problem with other db-migration steps
```
git checkout 53b4e8bcf49cb713ac81afffd426a86d19b0f826
git cherry-pick f7366e53922200a29b50c6551f57b7e70d24a2fa
git cherry pick 1d6cd7bf95dcdf3a0d9c81b0d79c5b0d439bfd75
```

install the plugin check db:

```

| xoct_md_field_event | CREATE TABLE `xoct_md_field_event` (
  `id` bigint(20) NOT NULL,
  `field_id` varchar(128) NOT NULL,
  `title_de` varchar(256) NOT NULL,
  `title_en` varchar(256) NOT NULL,
  `visible_for_permissions` varchar(512) NOT NULL,
  `required` tinyint(4) NOT NULL,
  `read_only` tinyint(4) NOT NULL,
  `prefill` varchar(128) NOT NULL,
  `sort` bigint(20) NOT NULL,
  `values` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci |
```

update the plugin to the commit of the metadata enhancement https://github.com/opencast-ilias/OpenCast/commit/72145229932c9a5f314adb8ddc6658aad51188fe

```
git checkout 72145229932c9a5f314adb8ddc6658aad51188fe
git cherry-pick f7366e53922200a29b50c6551f57b7e70d24a2fa
git cherry pick 1d6cd7bf95dcdf3a0d9c81b0d79c5b0d439bfd75
```

no update offered.. The DB still is:

```

| xoct_md_field_event | CREATE TABLE `xoct_md_field_event` (
  `id` bigint(20) NOT NULL,
  `field_id` varchar(128) NOT NULL,
  `title_de` varchar(256) NOT NULL,
  `title_en` varchar(256) NOT NULL,
  `visible_for_permissions` varchar(512) NOT NULL,
  `required` tinyint(4) NOT NULL,
  `read_only` tinyint(4) NOT NULL,
  `prefill` varchar(128) NOT NULL,
  `sort` bigint(20) NOT NULL,
  `values` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci |
```
</p>
</details>

**Comment by dagraf** [comment]
This issue appears also on our installation, but only with release_8. It does not appear with release_7. @chfsx: Can you have a look at it? Thx.

**Comment by dagraf** [comment]
After deploying https://github.com/opencast-ilias/OpenCast/pull/255, the error no longer appears. Therefore, I close this issue.
