### ISSUE TITLE
Upload / Addition of a Video fails when 'upload via ingest nodes' is active

### ISSUE THREAD

**Issue by tkurze** [opencast-ilias/OpenCast#254]
**Describe the bug**
When the 'upload via ingest-nodes'-option is active in advanced settings, adding of a video in an OpenCast object fails; nothing is added to the series / Opencast object in Ilias.

**To Reproduce**
1. Go to Settings -> Advanced and make sure 'upload via ingest-nodes'-option is active
2. Create a new opencast object (or select an existing series, probably the same...) 
3. Select a file to upload, insert all necessary meta-data
4. Click upload and -> see error

**Expected behavior**
No error should be thrown; video should be added and OC-WF should be started.

**Additional info**
If the 'upload via ingest-nodes'-option is *not set* the upload succeeds and the video processing wf in Opencast ist started.

**Log**
Error thrown with message "Cannot access private property ilXmlWriter::$xmlStr"
 
Stacktrace:
#13 Error in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Util/Transformator/MetadataToXML.php:76
#12 srag\Plugins\Opencast\Util\Transformator\MetadataToXML:getXML in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Util/FileTransfer/OpencastIngestService.php:45
#11 srag\Plugins\Opencast\Util\FileTransfer\OpencastIngestService:ingest in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/Event/EventAPIRepository.php:109
#10 srag\Plugins\Opencast\Model\Event\EventAPIRepository:upload in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventGUI.php:638
#9 xoctEventGUI:create in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:74
#8 xoctGUI:performCommand in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventGUI.php:279
#7 xoctEventGUI:performCommand in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventGUI.php:239
#6 xoctEventGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#5 ilCtrl:forwardCommand in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php:169
#4 ilObjOpenCastGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#3 ilCtrl:forwardCommand in /srv/ilias/ilias/Services/Repository/PluginSlot/class.ilObjPluginDispatchGUI.php:61
#2 ilObjPluginDispatchGUI:executeCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:199
#1 ilCtrl:forwardCommand in /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php:174
#0 ilCtrl:callBaseClass in /srv/ilias/ilias/ilias.php:24
 

**Environment (please complete the following information):**
 - ILIAS version: 8.9
 - PHP version: 8.?
 - Plugin version: 8.0.1
 - Opencast version 14.7.0
 - Browser: chrome

**Additional context**
- Our test opencast setup has an active ingest node, which worked fine with outher versions of the OC plugin.
- This issue may be low priority, as a simple workaround is to not use the ingest nodes. This might not be true for larger setups...

**Comment by dagraf** [comment]
After deploying https://github.com/opencast-ilias/OpenCast/pull/255, the error no longer appears. Therefore, I close this issue.
