### ISSUE TITLE
Release 8(.0.1): error when changing OC object settings

### ISSUE THREAD

**Issue by tkurze** [opencast-ilias/OpenCast#256]
**Describe the bug**

**To Reproduce**
1. Go to 'Settings of an OC Object (in a course)'
2. Change any of the settings; or input a description, 
3. Click save

**Expected behavior**
No error should be raised; changes should be saved and persisted

**Screenshots**
![image](https://github.com/opencast-ilias/OpenCast/assets/1611618/bf6aecaa-ff59-4de6-9606-db52708a3469)

**Log**
Whoops\Exception\ErrorException: Undefined array key "publish_on_video_portal" in /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/UI/ObjectSettings/ObjectSettingsFormItemBuilder.php:239 Stack trace: #0 /srv/ilias/ilias/Services/Init/classes/class.ilErrorHandling.php(443): Whoops\Run->handleError(2, 'Undefined array...', '/srv/ilias/ilia...', 239) #1 /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/UI/ObjectSettings/ObjectSettingsFormItemBuilder.php(239): ilErrorHandling->handlePreWhoops(2, 'Undefined array...', '/srv/ilias/ilia...', 239) #2 [internal function]: srag\Plugins\Opencast\UI\ObjectSettings\ObjectSettingsFormItemBuilder->srag\Plugins\Opencast\UI\ObjectSettings\(Array) #3 /srv/ilias/ilias/src/Refinery/Custom/Transformation.php(49): call_user_func(Object(Closure), Array) #4 /srv/ilias/ilias/src/Refinery/DeriveApplyToFromTransform.php(42): ILIAS\Refinery\Custom\Transformation->transform(Array) #5 /srv/ilias/ilias/src/Data/Result/Ok.php(84): ILIAS\Refinery\Custom\Transformation->ILIAS\Refinery\(Array) #6 /srv/ilias/ilias/src/Refinery/DeriveApplyToFromTransform.php(46): ILIAS\Data\Result\Ok->then(Object(Closure)) #7 /srv/ilias/ilias/src/UI/Implementation/Component/Input/Field/Input.php(344): ILIAS\Refinery\Custom\Transformation->applyTo(Object(ILIAS\Data\Result\Ok)) #8 /srv/ilias/ilias/src/UI/Implementation/Component/Input/Field/Group.php(184): ILIAS\UI\Implementation\Component\Input\Field\Input->applyOperationsTo(Object(ILIAS\Data\Result\Ok)) #9 /srv/ilias/ilias/src/UI/Implementation/Component/Input/Field/Group.php(171): ILIAS\UI\Implementation\Component\Input\Field\Group->withInput(Object(ILIAS\UI\Implementation\Component\Input\Container\Form\PostDataFromServerRequest)) #10 /srv/ilias/ilias/src/UI/Implementation/Component/Input/Container/Form/Form.php(90): ILIAS\UI\Implementation\Component\Input\Field\Group->withInput(Object(ILIAS\UI\Implementation\Component\Input\Container\Form\PostDataFromServerRequest)) #11 /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Series/class.xoctSeriesGUI.php(165): ILIAS\UI\Implementation\Component\Input\Container\Form\Form->withRequest(Object(GuzzleHttp\Psr7\ServerRequest)) #12 /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php(74): xoctSeriesGUI->updateGeneral() #13 /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php(68): xoctGUI->performCommand('updateGeneral') #14 /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Series/class.xoctSeriesGUI.php(100): xoctGUI->executeCommand() #15 /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php(199): xoctSeriesGUI->executeCommand() #16 /srv/ilias/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php(149): ilCtrl->forwardCommand(Object(xoctSeriesGUI)) #17 /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php(199): ilObjOpenCastGUI->executeCommand() #18 /srv/ilias/ilias/Services/Repository/PluginSlot/class.ilObjPluginDispatchGUI.php(61): ilCtrl->forwardCommand(Object(ilObjOpenCastGUI)) #19 /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php(199): ilObjPluginDispatchGUI->executeCommand() #20 /srv/ilias/ilias/Services/UICore/classes/class.ilCtrl.php(174): ilCtrl->forwardCommand(Object(ilObjPluginDispatchGUI)) #21 /srv/ilias/ilias/ilias.php(24): ilCtrl->callBaseClass() #22

**Environment (please complete the following information):**
 - ILIAS version: 8.9
 - PHP version: 8.?
 - Plugin version: 8.0.1
 - Opencast version 14.7.0
 - Browser: chrome

**Comment by dagraf** [comment]
@tkurze: Since your error seems to be connected with "publish_on_video_portal": What do you have configured in the tab "Video Portal"?

**Comment by dagraf** [comment]
Since there was no answer to my question above and there where quite some changes in the plugin, I close this issue.

@tkurze: Feel free to reopen it if you still observe this issue. Thx.
