### ISSUE TITLE
Release 8: Import old configuration throws error

### ISSUE THREAD

**Issue by ferishili** [opencast-ilias/OpenCast#261]
**Describe the bug**
When upgrading to (fresh install) release_8, importing old settings throws error stating: `nodeValue` on null

**To Reproduce**
1. Fresh install ILIAS 8 and release_8 of the plugin
2. Try to import configuration from an old plugin!
3. See error

**Expected behavior**
The case if null for the configs should be handled (with default values) in order to have a smooth export from old / import to release_8 experience

**Log**
```
[b128o] [2024-03-28 08:13:18.942225] ilias_8_root.ERROR: Whoops\Handler\CallbackHandler::handle:398 2 Attempt to read property "nodeValue" on null in /release_8/src/Model/Config/PluginConfig.php:337#0 /release_8/ilias/Services/Init/classes/class.ilErrorHandling.php(459): Whoops\Run->handleError(2, 'Attempt to read...', '/Users/farbod/W...', 337)
#1 /release_8/src/Model/Config/PluginConfig.php(337): ilErrorHandling->handlePreWhoops(2, 'Attempt to read...', '/Users/farbod/W...', 337)
#2 /release_8/classes/Conf/Export/class.xoctConfExportGUI.php(62): srag\Plugins\Opencast\Model\Config\PluginConfig::importFromXML('/private/var/fo...')
```

**Environment (please complete the following information):**
 - ILIAS version: v8.10
 - PHP version: 8.0.30
 - Plugin version: release_8
 - Opencast version 15.3
 - Browser: Firefox

**Additional context**
Did not check for release_7, it might be needed there as well!

**Comment by dagraf** [comment]
Thx for the bugreport. I can reproduce it on our ILIAS8 installation when importing an export from an old version of the plugin (5.1.1).
I will test the bugfix soon.

**Comment by dagraf** [comment]
After deploying https://github.com/opencast-ilias/OpenCast/pull/262 the bug does not appear anymore. I therefore close this issue.
