### ISSUE TITLE
Create series element fails with error Ilias7.29 + release_7 (68679d1, 2024-03-21)

### ISSUE THREAD

**Issue by marcusm7** [opencast-ilias/OpenCast#269]
**Describe the bug**
Creating a new Opencast element fails with an error. 

**To Reproduce**
1. Within a course add a new opencast object
2. choose existing/ new series (doesn't matter)
3. Click save/ apply 
4. The operation fails and an ilias error is displayed
5. a broken series object is created in the course

vgl: https://matrix.to/#/!gFRPgVuHvHALFDrHGc:matrix.org/$6i59eEu80iZbhxAT9w0LonFO76Q3ULXK0VKu1VxNQGU?via=matrix.org&via=chat.virtuos.uni-osnabrueck.de&via=matrix.im

**Expected behavior**
A series object is created. 

**Screenshots**

**Log**
```
TypeError thrown with message "Argument 1 passed to srag\Plugins\Opencast\Model\User\xoctUser::__construct() musTypeError thrown with message "Argument 1 passed to srag\Plugins\Opencast\Model\User\xoctUser::__construct() mus
t be of the type int, string given, called in /.../ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/User/xoctUser.php on line 111"

Stacktrace:
#13 TypeError in /.../ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/User/xoctUser.php:120
#12 srag\Plugins\Opencast\Model\User\xoctUser:__construct in /.../ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Model/User/xoctUser.php:111
#11 srag\Plugins\Opencast\Model\User\xoctUser:getInstance in /.../ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastAccess.php:349
```

**Environment (please complete the following information):**
 - ILIAS version: 7.29
 - PHP version: 7.4.3-4ubuntu2.20
 - Plugin version: release_7 (68679d1, 2024-03-21)
 - Opencast version 14.4/ API: 1.9.0
 - Browser: firefox 123.01

**Additional context**

**Comment by marcusm7** [comment]
The PR https://github.com/opencast-ilias/OpenCast/pull/266/commits/44d64a5e9acd686bc1ab470aeb13eb772edd31e3 
seems to resolve the above mentioned error.

(It does in my case. Creation new opencast objects works now.)

**Comment by chfsx** [comment]
as @marcusm7 mentioned, this should be fixed with https://github.com/opencast-ilias/OpenCast/commit/44d64a5e9acd686bc1ab470aeb13eb772edd31e3

**Comment by dagraf** [comment]
Fixed. Therefore I close it.
