### ISSUE TITLE
No upload progress bar shows up, and upload of larger video stucks (V 4.0.1)

### ISSUE THREAD

**Issue by DZenker** [opencast-ilias/OpenCast#27]
In all former Opencast plugin versions, an upload progress bar was shown during upload of a video. In 4.0.1, there's is no upload progress bar anymore, therefore there is no feedback for the user about the current upload status. The behaviour is as follows: after selecting a video file, the "save" button gets deactivated until the transfer of the video is completed.
Is this an intended behaviour or an configuration issue - maybe there is a certain PHP extension missing in our setting? (e.g. PECL or APC).

Furthermore, the video upload stucks with larger files, i.e. the save button remains in its disabled state even after the complete transfer of the video, and as a result there is no way to finalize the video upload step. For instance, upload of a approx. 30 MB video file succeeds and in the browser's developer console an "Upload complete" response is shown for the XHR post request. In contrast, upload of a approx. 100 MB video file results in a permanently disabled save button, and there is also never an "upload complete" message displayed for the post request.

**Comment by DZenker** [comment]
Can anyone confirm this problem? Or, is this issue specific for our setting (due to configuration, missing PHP extension etc.)?

**Comment by ebbertd** [comment]
I tried to reproduce this with a video of 160MB. I don't see a progress bar. The save button also becomes disabled. But, as soon as I click in another field, e.g. the title the save button is enabled again and I can upload the video.

**Comment by DZenker** [comment]
Now I tried this once again from the university network (with faster upload speed compared to my home office), and in this scenario it's working as the save button is enabled after transfer of the video has been finished. Thus, maybe this is caused by some kind of timeout, when the upload speed is too low and the upload process takes too long.
IMO, given that this is primarily used by teachers with limited technical expertise and possibly slow internet connection in the home office, the upload behavior is very unfavorable and in my opinion a clear step backwards compared to the previous versions with chunk upload and visual feedback of the upload process.

Additionally, I've just realized that there is a size limit of 256 MB for the video file which is much to low - is this configurable somewhere?

**Comment by DZenker** [comment]
Hi David,

since you wanted to hand the whole thing over to your developer, here's a hint: a special js library was used for the chunk upload in the previous versions: 
https://www.plupload.com/
https://github.com/fluxapps/OpenCast/tree/v3.7.4/js

Greetings, Dietmar

**Comment by reiferschris** [comment]
We already contracted Elan e.V. to fix this issue. It is currently being worked on. Let's wait until that is finished and if any issues remain.

**Comment by ferishili** [comment]
Hi @chfsx 
Here again the place to increase the upload file size:
https://github.com/ILIAS-eLearning/ILIAS/blob/1d37af4849c8d0ac6bd6729faf28e92b980ded99/libs/bower/bower_components/dropzone/dist/dropzone.js#L228

This file also needs to have the change accordingly: 
https://github.com/ILIAS-eLearning/ILIAS/blob/release_7/libs/bower/bower_components/dropzone/dist/min/dropzone.min.js

**Comment by DZenker** [comment]
Hi,

this is a default setting which probably could be overwritten when this function is called or the event is initiated. There's also an option to activate a chunk upload (_chunking:false|true_).

**Comment by chfsx** [comment]
Hello together

At our last meeting, I was given the task of looking at possible options. I tried to find out which wig would be the best to use to enable a chunk-upload again.

In the Opencast plugin, the old form implementation was replaced by new UI\Inputs from the ILIAS UI service. This is basically a good decision and the right way. All forms in the ILIAS core should also be rebuilt in this way.

As of ILIAS 6, the UI\Inputs know a UI\Input\File. This is also used in Opencast. The input uses a JS library that would also support chunk uploads. In ILIAS, however, this function cannot be addressed. I therefore suggest the following procedure:

- We write an extension of the input in the plugin and enable the chunk upload there.
- For ILIAS 8 or 9 (still to be checked) we transfer this function into the core, so that later the plugin-internal input is no longer needed.

**Comment by dagraf** [comment]
Thx @chfsx, for looking into it and your suggestion. What do others think about this suggestion? I lack the necessary technical knowledge to leave my thoughts about it...

**Comment by DZenker** [comment]
IMO this suggestion would be the best option. Since other objects/plugins such as the cloud/OneDrive object would also benefit from a chunk upload of large files, it would be beneficial to integrate this into the core.

**Comment by reiferschris** [comment]
Solved with https://github.com/opencast-ilias/OpenCast/pull/66
