### ISSUE TITLE
The Opencast object cannot be deleted

### ISSUE THREAD

**Issue by ralede** [opencast-ilias/OpenCast#275]
The Opencast object cannot be deleted. An error message appears.

**To Reproduce**
1. Create a new or choose an existing Opencast object
2. Click on 'Delete'
3. The error message appears and the Opencast object still exists

**Expected behavior**
The Opencast object should be deleted without an error message

**Log**
TypeError thrown with message "Argument 2 passed to ilObjOpenCastGUI::showDeleteConfirmation() must be of the type bool, null given, called in /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/trait.ilObjShowDuplicates.php on line 44"

Stacktrace:
#8 TypeError in /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/trait.ilObjShowDuplicates.php:52
#7 ilObjOpenCastGUI:showDeleteConfirmation in /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/trait.ilObjShowDuplicates.php:44
#6 ilObjOpenCastGUI:deleteObject in /var/www/ilias/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php:187
#5 ilObjOpenCastGUI:executeCommand in /var/www/ilias/Services/UICore/classes/class.ilCtrl.php:217
#4 ilCtrl:forwardCommand in /var/www/ilias/Services/Repository/classes/class.ilRepositoryGUI.php:375
#3 ilRepositoryGUI:show in /var/www/ilias/Services/Repository/classes/class.ilRepositoryGUI.php:337
#2 ilRepositoryGUI:executeCommand in /var/www/ilias/Services/UICore/classes/class.ilCtrl.php:217
#1 ilCtrl:forwardCommand in /var/www/ilias/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /var/www/ilias/ilias.php:23

**Environment (please complete the following information):**
 - ILIAS version: 7.29 2024-03-19
 - PHP version: PHP7.4-FPM
 - Plugin version: 7.0.3
 - Opencast version 14.9.0
 - Browser: Firefox, Chrome

**Comment by dagraf** [comment]
I can reproduce this bug on our installation. @chfsx Can you have a look at it in fix it as soon as possible? Thx!

**Comment by rfcmaXi** [comment]
https://github.com/opencast-ilias/OpenCast/blob/release_7/classes/trait.ilObjShowDuplicates.php#L44
$a_error?

**Comment by dagraf** [comment]
Testing of the bugfix in https://github.com/opencast-ilias/OpenCast/pull/284 by @tscheere was succesfull. Therefore, I close this issue.
