### ISSUE TITLE
Type Error in Administration Switchable Group

### ISSUE THREAD

**Issue by Amstutz** [opencast-ilias/OpenCast#278]
**Describe the bug**
With the latest issue, there is a type error for the Switchable group

**To Reproduce**
1. Go to the Plugins Administration
2. Click on the Player Subtap

**Log**
<img width="1380" alt="image" src="https://github.com/opencast-ilias/OpenCast/assets/1866896/8ecf2911-b306-4b69-bee0-3dc2ea58d1c9">

**Comment by chfsx** [comment]
See #283

**Comment by dagraf** [comment]
Fixed for ILIAS 8.12 and higher with new version of the plugin (v8.0.4). More information: https://groups.google.com/a/opencast.org/g/lms/c/xj31oGwvqnQ/m/Guj9FenaAQAJ
