### ISSUE TITLE
Configured metadata fields get erased when updating the plugin

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#280]
**Describe the bug**
The last three times we did an update of the plugin on our ILIAS 8 installation whe had to configure the metadata fields for events and series from scratch. Somehow they got lost/erased by the update. Could there be something wrong with (one of) the update step?

**To Reproduce**
1. Have some metadata fields for events and/or series configured
2. Update the plugin on your installation to the latest version.
3. Go to plugin config and open tab "Metadata"
4. See that the both tables for Events and Series are empty

**Expected behavior**
Updating the plugin should NOT have any impact on the configured metadata fields.

**Log**
If you have it please attach the relevant log.

**Environment (please complete the following information):**
 - ILIAS version: v8.10 2024-03-19
 - PHP version: [e.g. PHP 7.4.3]
 - Plugin version: 8.0.3
 - Opencast version. 15
 - Browser: Firefox

**Additional context**
Bug does NOT appear on the release_7.

**Comment by chfsx** [comment]
@dagraf just to be sure i'm trying the same thing as you and because i can't reproduce the behaviour so far: by updating do you mean from any 8.0.x to a newer 8.0.y version? we can otherwise discuss this via matrix

**Comment by dagraf** [comment]
One update where we had to reconfigure the metadata was from 8.0.1 to 8.0.3. Unfortunately, I can no longer reproduce the problem. I am therefore closing the ticket and would reopen it if necessary if the error occurs again.
