### ISSUE TITLE
Memorization of last position in video is not per video

### ISSUE THREAD

**Issue by mic-men** [opencast-ilias/OpenCast#289]
**Describe the bug**
When leaving the Paella Player in the middle of a video, the last position is remembered. Unfortunately this position is not remembered per video, i.e. when playing **another** video afterwards it starts from the remembered position of the last one.

**To Reproduce**
1. Go to 'Play' for a video
2. The player with the thumbnail is visible. Now click the Play button.
3. Play some time, pause the video, remember the time stamp the video has stopped.
4. Leave video and open another one for playing.
5. The player with the thumbnail is visible. Now click the Play button.
6. The new video starts from the time position the previous one has been left.

**Expected behavior**
A new video should play right from the start resp. the position I left exactly this video the last time.

**Environment (please complete the following information):**
 - ILIAS version:  7.30
 - PHP version: PHP 7.4
 - Plugin version: 7.0.3 (May 2024)
 - Opencast version: 14.6.
 - Browser: Firefox, Chromium

**Note**
Until there is a solution a certain flag in the _config.json_ of the player should be set to false. Unfortunately I do not know which one, please someone else add this info!

**Comment by mic-men** [comment]
In order to disable this buggy feature, set 

> "restoreLastTime": {
>  "enabled": false,

in _config.json_
See [here](https://github.com/opencast-ilias/OpenCast/blob/release_7/js/opencast/src/Paella/config/config.json#L42-L44).

**Comment by dagraf** [comment]
@chfsx Is this a bug you would fix or should we ask @ferishili to do so, since it concerns the Paella player?

**Comment by ferishili** [comment]
I will take care of it

**Comment by dagraf** [comment]
After pulling https://github.com/opencast-ilias/OpenCast/pull/295 (for Release 8), the bug no longer exists. I therefore close this issue.

@mic-men Can you please test the PR https://github.com/opencast-ilias/OpenCast/pull/296 for Release 7? Thx!

**Comment by mwizgall** [comment]
> After pulling #295 (for Release 8), the bug no longer exists. I therefore close this issue.
> 
> @mic-men Can you please test the PR #296 for Release 7? Thx!



> After pulling #295 (for Release 8), the bug no longer exists. I therefore close this issue.
> 
> @mic-men Can you please test the PR #296 for Release 7? Thx!

@dagraf Michael has updated the plugin recently and I tested it afterwards. The issue still exists for ILIAS v7.30.1.

**Comment by ferishili** [comment]
Make sure that your browser cache is clear

**Comment by mwizgall** [comment]
@ferishili If I compare two different Videos the problem still exists. 
1. Video 1 starts at 00:00. 
2. Video 2 starts at the point Video 1 ended. 
3. I clear the browser cache
4. The first Video I open (Video 1 e.g. ), starts at 00:00 as it should. 
5. Unfortunately Video 2 starts at the position I left Video 1 in step 4.

**Comment by ferishili** [comment]
We need to look deeper into this problem, it appears that disabling the config `restoreLastTime` is not enough!

**Comment by reiferschris** [comment]
Hey @mwizgall could you please check the contents of your config.json after clearing the cache in your browsers dev-tools? They should appear in the network tab where you can see the response and the contents of that file

**Comment by mwizgall** [comment]
Hey @reiferschris,

thank's for your help. 
Unfortunately I couldn't find the requested information. 
I don't have admin access on our system, so I just have the information from Michael, that the plugin has been updated. 

The network-tab in Google and Firefox (After clearing the cache and accessing ILIAS + Paella player twice) doesn't contain the communication with the 'config.json' (Screenshot 1/2).
In the search for the debugger I found the config.json (Screenshot 3/4), but I dont think that the information is helpful.
 
![DevTools](https://github.com/opencast-ilias/OpenCast/assets/157113406/61e3b1e3-fe64-434c-bf18-5a4616619fdc)
![DevTools_Firefox](https://github.com/opencast-ilias/OpenCast/assets/157113406/ac09aeb4-8c97-4a5e-a17e-cc036dc7b3de)
![Config js](https://github.com/opencast-ilias/OpenCast/assets/157113406/e244b5a5-b0d3-47a5-a50d-c7575ab8182a)
![Network-Tab](https://github.com/opencast-ilias/OpenCast/assets/157113406/6507b4ba-5264-41bf-a0f2-56a1622468c2)

Could you give me a more detailed advise, how I can find the neccessary information?

**Comment by michaellenhart** [comment]
Vielen Dank für Ihre Nachricht.
Ich bin aktuell im Urlaub und erst am 08.07.24 wieder für Sie erreichbar.
In der Zwischenzeit können Sie sich bei dringenden Anfragen an ***@***.*** wenden.  
Mit freundlichen Grüßen
Michael Lenhart

***

Tag für die exzellente Lehre 2024 am 20. September am Campus Deutz unter dem Motto "Transformatives Lernen für nachhaltige gesellschaftliche Lösungen"
- Jetzt noch bis zum 31. Juli 2024 anmelden!

***

B.Sc. Michael Lenhart

Zentrum für Lehrentwicklung (ZLE)
IT-Admin
T: +49 221-8275-3736
E: ***@***.***

Technische Hochschule Köln
Campus Deutz
Betzdorfer Straße 2
50679 Köln
Raum: ZO-5-11

https://www.th-koeln.de

**Comment by reiferschris** [comment]
Hi @mwizgall 
try this please:
1. Open a video in a new tab
2. Open the dev tools, network tab
3. search for the check box "disable cache" or something like that (both firefox and chrome have this option)
4. reload the page, ideally delete the history in the dev tools before that to see only the traffic after the reload.

**Comment by snoesberger** [comment]
Have a look at the following comment: https://github.com/polimediaupv/paella-core/issues/367#issuecomment-2199704776
It seems that the plugin does not correctly implement the `getVideoId` function in the initialisation parameters, which is needed to store the last video position per event. @ferishili can you please have a look at this?

**Comment by mic-men** [comment]
With the info @snoesberger found we should try to enable the feature.

**Comment by ferishili** [comment]
Hi, good that you reopened this, I am ready to start the fix as soon as I get a go by @snoesberger or @dagraf

**Comment by dagraf** [comment]
@ferishili: You have our 'Go'. Thank your for looking into it.
