### ISSUE TITLE
Too much unnecessary subtitle details in paella player

### ISSUE THREAD

**Issue by ferishili** [opencast-ilias/OpenCast#292]
#### Description
The subtitle names in the ILIAS paella player shows unnecessary details of the captions (when they have tag details) devided by "-" e.g. `eng - (Manual) - (Subtitle) ` which does not match the Opencast paella player that only shows the language name!

**To Reproduce**
1. Make sure you have a video that has captions (subtitles) using new mechanism with tags
2. Play that video in ILIAS and check the caption name
3. Play that video in Opencast and check the caption name there

**Expected behavior**
The ILIAS paella player should provide only the language name just like paella player in opencast.

**Environment (please complete the following information):**
 - ILIAS version: v7 or v8
 - Plugin version: release_7 & release_8 are affected
 - Opencast version 15 (must)
 - Browser: all

**Comment by reiferschris** [comment]
Hi, 
I don't think this data is unnecessary. It can and IMHO should be used at least partially to indicate e.g. that a subtitle was generated by whisper/automated.
We specifically added this when developing the feature to show subtitles to tell the user about the quality of the subtitles, so they can adjust their expectations.
I'm strongly against removing that as a feature, I'm not opposed however to make it configurable which parts of the tags are shown .

**Comment by ferishili** [comment]
+1 configurable
@dagraf what do you think?

**Comment by reiferschris** [comment]
See for example youtube where they show how the subtitle was generated:
![image](https://github.com/opencast-ilias/OpenCast/assets/34450887/a8274cc5-ed0e-4230-b741-4af0d30524bd)

**Comment by dagraf** [comment]
I agree, the information is not unnecessary. Therefore, the goal of fixing this issue should not be to only show the language name but show all relevant information in a suitable form. See for example the same video played in Opencast (above) and in ILIAS (below). I would expect the paella player in ILIAS to show the information in the same way as it is shown in the paella player in Opencast. 

Opencast:
<img width="264" alt="Bildschirmfoto 2024-06-11 um 13 52 05" src="https://github.com/opencast-ilias/OpenCast/assets/15246287/766dac9b-73d3-4d8c-abc2-845c2288af59">

ILIAS:
<img width="254" alt="Bildschirmfoto 2024-06-11 um 13 51 37" src="https://github.com/opencast-ilias/OpenCast/assets/15246287/22382104-e1ae-4d43-a4b0-c07d081ea0cb">

**Comment by dagraf** [comment]
After pulling https://github.com/opencast-ilias/OpenCast/pull/295 (for Release 8), the bug no longer exists. I therefore close this issue.
