### ISSUE TITLE
Download of video by a right click should not be possible

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#293]
**Describe the bug**
With Paella 7, the videos can be downloaded using the right click and then "Save video". This should not be the case.

**To Reproduce**
1. Open a video
2. Make a right click
3. Choose "Save video as"

**Expected behavior**
It should not be possible to download the video that easily. Possible solution: The right click 

**Environment (please complete the following information):**
 - ILIAS version: v8.12 2024-05-28
 - Plugin version: 8.0.5
 - Opencast version: 15
 - Browser: Firefox

**Additional context**
It might be a solution, to make changes in paella-player.js (under: Prevent video download).

**Comment by dagraf** [comment]
Same question as in https://github.com/opencast-ilias/OpenCast/issues/289:

@chfsx Is this a bug you would fix or should we ask @ferishili to do so, since it concerns the Paella player?

**Comment by ferishili** [comment]
Since it is Paella related, I will take a look, but not sure if that is easy to prevent

**Comment by dagraf** [comment]
It is prevented in Paella 7 on our Opencast 15 we run on our Test-Opencast.

**Comment by reiferschris** [comment]
Paella docs regarding this are here: https://paellaplayer.upv.es/#/doc/mp4_video_plugin.md
@dagraf have you implemented this change from the docs?
Or are you referring to the fact that you don't use mp4 but instead stream via hls?

**Comment by dagraf** [comment]
> Paella docs regarding this are here: https://paellaplayer.upv.es/#/doc/mp4_video_plugin.md @dagraf have you implemented this change from the docs? Or are you referring to the fact that you don't use mp4 but instead stream via hls?

@snoesberger: Can you answer @reiferschris question?

**Comment by snoesberger** [comment]
> Paella docs regarding this are here: https://paellaplayer.upv.es/#/doc/mp4_video_plugin.md @dagraf have you implemented this change from the docs? Or are you referring to the fact that you don't use mp4 but instead stream via hls?

In Opencast this can easily be configured with the `preventVideoDownload`parameter in the Paella config file config.json. Setting this parameter to `true` will disable the right click menu in the player. It doesn't matter if you use mp4 or hls.

**Comment by dagraf** [comment]
After pulling https://github.com/opencast-ilias/OpenCast/pull/295 (for Release 8), the bug no longer exists. I therefore close this issue.
