### ISSUE TITLE
Update Paella player user tracking plugin to support Matomo Media Analytics plugin

### ISSUE THREAD

**Issue by snoesberger** [opencast-ilias/OpenCast#294]
Recently some improvements have been made to the Paella player user tracking plugin. The changes make it possible to send player statistics data to the Matomo Media Analytics plugin. Therefore, the latest version 1.42.4 of paella-user-tracking should be integrated into the Opencast plugin.

**Comment by ferishili** [comment]
Closed as completed in
Release 8: https://github.com/opencast-ilias/OpenCast/pull/295
Release 7: https://github.com/opencast-ilias/OpenCast/pull/296
