### ISSUE TITLE
changing series metadata leads to unnecessary acl update

### ISSUE THREAD

**Issue by tscheere** [opencast-ilias/OpenCast#297]
**Describe the bug**
When trying to change the metadata of the series (e.g. name of the series) the user looses the ownership of the series and the videos within

**To Reproduce**
1. Change the name of a series
2. If you are using the admin UI, you are no longer able to see the series/ video within the series

**Expected behavior**
The owner of the series should keep ownership.

**Environment (please complete the following information):**
 - ILIAS version: [v7.30.1 2024-05-28]
 - PHP version: [PHP 7.4.33]
 - Plugin version: [7.0.3]
 - Opencast version [14.9.0]
 - Browser: [chrome, firefox]

**Comment by dagraf** [comment]
I can not reproduce this issue on the community ILIAS (ILIAS: v7.30 2024-05-14; Opencast: 15). 

Can someone else reproduce this issue on their installations?

**Comment by ferishili** [comment]
There is a fix available for this issue in [this branch](https://github.com/elan-ev/ilias-opencast-plugin/tree/uni_bonn_issue_1)
I will provide it as PR later when it is confirmed.

The fix works more or less as a code and logic improvement, therefore, having it merge does not harm old behavior but to fix this issue.

**Comment by ferishili** [comment]
Hi @tscheere,
are you sure about closing this? The PR is not yet merged!

**Comment by tscheere** [comment]
@ferishili sorry about that, I'm reopening the issue.

**Comment by dagraf** [comment]
PR that fixes this issue got merged. I therefore close this issue.
