### ISSUE TITLE
missing closing square bracket in StandardPlayerDataBuilder.php

### ISSUE THREAD

**Issue by okaufman** [opencast-ilias/OpenCast#324]
With the newest Version of the release_8 Plugin I received this error:
ERROR: Whoops\Handler\CallbackHandler::handle:398 0 syntax error, unexpected token "private", expecting "]" in /var/www/ilias-next/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/Util/Player/StandardPlayerDataBuilder.php:38#0 /var/www/ilias-next/libs/composer/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()

 This happened when trying to access a livestream.

 - ILIAS version: 8.12
 - PHP version: 8.0
 - Plugin version: 8.1.0
 - Browser: firefox

**Comment by chfsx** [comment]
This issue comes from a bad resolved merge conflict, I fix that immediately

**Comment by chfsx** [comment]
Fixed in v8.1.1
