### ISSUE TITLE
Undefined array key "operation" when creating series

### ISSUE THREAD

**Issue by mic-men** [opencast-ilias/OpenCast#326]
**Describe the bug**
When a new series is created, an error is thrown: `Undefined array key "operation"`.
The error is thrown every time the series is selected. Old series are not affected.

**To Reproduce**
1. Create a new series via the ILIAS GUI.
2. Only a title is given, everything else is left with default settings.
3. Save
4. Error message is shown. The series is created at the OC side.
5.  The series is shown as ILIAS object. When clicking on it the error pops up again.

**Expected behavior**
The series should be created without error.

**Log**
>Whoops\Exception\ErrorException thrown with message "Undefined array key "operation""
>
>Stacktrace:
>#22 Whoops\Exception\ErrorException in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastAccess.php:389
>#21 ilErrorHandling:handlePreWhoops in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastAccess.php:389
#20 ilObjOpenCastAccess:isActionAllowedForRole in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventTableGUI.php:285
#19 xoctEventTableGUI:getOwnerColDefault in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventTableGUI.php:254
#18 xoctEventTableGUI:getAllColumns in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventTableGUI.php:442
#17 xoctEventTableGUI:getSelectableColumns in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Table/classes/class.ilTable2GUI.php:287
#16 ilTable2GUI:determineSelectedColumns in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Table/classes/class.ilTable2GUI.php:173
#15 ilTable2GUI:__construct in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventTableGUI.php:107
#14 xoctEventTableGUI:__construct in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/src/UI/EventTableBuilder.php:84
#13 srag\Plugins\Opencast\UI\EventTableBuilder:table in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventGUI.php:523
#12 xoctEventGUI:getTableGUI in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventGUI.php:518
#11 xoctEventGUI:asyncGetTableGUI in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventGUI.php:401
#10 xoctEventGUI:indexList in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventGUI.php:360
#9 xoctEventGUI:index in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:74
#8 xoctGUI:performCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventGUI.php:279
#7 xoctEventGUI:performCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Event/class.xoctEventGUI.php:239
#6 xoctEventGUI:executeCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/UICore/classes/class.ilCtrl.php:203
#5 ilCtrl:forwardCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilObjOpenCastGUI.php:169
#4 ilObjOpenCastGUI:executeCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/UICore/classes/class.ilCtrl.php:203
#3 ilCtrl:forwardCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Repository/PluginSlot/class.ilObjPluginDispatchGUI.php:61
#2 ilObjPluginDispatchGUI:executeCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/UICore/classes/class.ilCtrl.php:203
#1 ilCtrl:forwardCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/ilias.php:24

>-- GET Data --

>^@ILIAS\HTTP\Wrapper\SuperGlobalDropInReplacement^@throwOnValueAssignment: 
>^@ILIAS\Refinery\KeyValueAccess^@raw_values: Array
                         (
                             [baseClass] => ilobjplugindispatchgui
                             [cmdNode] => pu:pm:18w
                             [cmdClass] => xoctEventGUI
                             [ref_id] => 13344
                             [async] => true
                             [limit] => 100
                         )
                         
>^@ILIAS\Refinery\KeyValueAccess^@trafo: ILIAS\Refinery\KindlyTo\Transformation\StringTransformation Object
                         (
                         )
                         

>-- POST Data --

>^@ILIAS\HTTP\Wrapper\SuperGlobalDropInReplacement^@throwOnValueAssignment: 
>^@ILIAS\Refinery\KeyValueAccess^@raw_values: Array
                         (
                         )
                         
>^@ILIAS\Refinery\KeyValueAccess^@trafo: ILIAS\Refinery\KindlyTo\Transformation\StringTransformation Object
                         (
                         )

**Environment (please complete the following information):**
 - ILIAS version: v8.13
 - PHP version: PHP 8.0.30
 - Plugin version: v8.1.1
 - Opencast version 14.6
 - Browser: Firefox

**Additional context**
Maybe there is a relation to issue #311 ?

**Comment by rfcmaXi** [comment]
Confirmed with Plugin version: v8.1.1 / PHP version: PHP 8.0.30

**Comment by rfcmaXi** [comment]
In our test installation, I no longer receive the error after the plugin-update has been executed via CLI Command (without mentioned pr)

**Comment by mic-men** [comment]
The proposed fix #329 solves the problem in our environment.
