### ISSUE TITLE
New Installation fails

### ISSUE THREAD

**Issue by ferishili** [opencast-ilias/OpenCast#330]
Trying to install the plugin > v8.1.0 via CLI, the process fails.
 
**To Reproduce**
1. Make sure that you are going to fresh install the plugin
2. in ilias root directory peform the command 
`php setup/setup.php install --config=[path/to/config] --plugin=OpenCast`
3. See the error

**Expected behavior**
The fresh installation must go through without error!

**Screenshots**

![Screenshot 2024-07-25 at 16 25 59](https://github.com/user-attachments/assets/850bd6e9-e14e-4a43-bca4-e3494fbdae85)

**Environment (please complete the following information):**
 - ILIAS version: 8.13
 - PHP version: 8.0.30
 - Plugin version: 8.1.1

**Additional context**
This issue comes from the fact that we introduced `ilOpenCastDBUpdateSteps` while still using old `dbupdate` for the first installation!

**Comment by ferishili** [comment]
Hi @chfsx,
regarding your suggestion with `PHP_SAPI === 'cli'` to control the cli process. I would say, it is an important thing here to fix this issue, since the plugin could not be installed without CLI in ILIAS >= 8 (or at least I am not aware of other ways). What is your opinion?

**Comment by reiferschris** [comment]
Would this get us closer to this dream of mine? https://github.com/opencast-ilias/OpenCast/issues/170

**Comment by ferishili** [comment]
I did provide a small code block which will do the trick, but did not test it through:

FIle: classes/class.ilOpenCastPlugin.php

```
public function install(): void
{
    if (PHP_SAPI === 'cli') {
        $this->update();
    }
    parent::afterInstall();
}
```
