### ISSUE TITLE
Live Streams / Chat configuration

### ISSUE THREAD

**Issue by mic-men** [opencast-ilias/OpenCast#333]
**Describe the bug**
In the plugin configuration deactivating the option "Live Streams" while the suboption "Chat aktivieren" ist still active leads to unexpected/buggy behaviour.

**To Reproduce**
1. In plugin config activate  "Einstellungen > Aufzeichnungen > Live-Streams".
2. Activate suboption  "Chat aktivieren"
3. Save.
4.  In plugin config **deactivate**  "Einstellungen > Aufzeichnungen > Live-Streams".

**Expected behavior**
Deactivating Live Streams should also deactivate the chat functionality. The option should not be visible in the series settings.
Instead, series still show "Chat bei Live Streams" option. When this option in a serie is activated, no videos in the serie can be played (empty white screen)! 
The correct behaviour is given when "Chat aktivieren" is deactivated before deactivating "Live-Streams" in plugin config.

**Environment**
 - ILIAS version:  7 and 8
  - PHP version: 7 and 8
 - Plugin version: from 5 to latest
 - Opencast version 14.6.

**Comment by dagraf** [comment]
@ferishili As disscussed in community meeting: Can you please have a look here? Thx!
