### ISSUE TITLE
Workflows: Checkboxes in configuration panels do not work

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#343]
**Describe the bug**
We have configured the workflows "duplicate-event" and "generate-caption". In both configuration panels there is a checkbox which does not work when a user starts this workflow. It seems that always the same attribute "false" gets sent.

duplicate-event: The checkbox "Do not use copy suffix" has no effect.
generate-caption: The checkbox "Publish event with newly created captions" has no effect

**To Reproduce**
1. Have both workflows "duplicate-event" and "generate-captions-and-publish" configured with acitvated configuration panels
2. Go to an Opencast series
3. Click on "Action" > "Start workflow"
4. Choose the workflow "Duplicate event" and activate the checkbox "Do not use copy suffix" > hit on save
5. See that the created copy has the suffix "(copy 1)" in its title, which should not be the case

**Expected behavior**
The checkboxes should work properly when activated.

**Environment (please complete the following information):**
 - ILIAS version: v8.13 2024-06-25
 - Plugin version: 8.1.4
 - Opencast version: 15
 - Browser: Firefox

**Comment by chfsx** [comment]
@dagraf how can I configure this situation with https://opencast-test.ilub.unibe.ch/? It's seems as if those workflows are not avaibale there or there is another issue...

**Comment by reiferschris** [comment]
Hi, i've seen something similiar within Opencast itself before: https://github.com/opencast/opencast/issues/5366
Recently I had the exact same issue again, also directly in Opencast but the plugin uses the same wokflow configuration panel as opencast itself.

**Comment by dagraf** [comment]
@snoesberger Can you please configure the "duplicate-event" workflow on https://opencast-test.ilub.unibe.ch/ ? Thx!

**Comment by snoesberger** [comment]
> @snoesberger Can you please configure the "duplicate-event" workflow on https://opencast-test.ilub.unibe.ch/ ? Thx!

The "duplicate-event" workflow is already configured and is accessible to everyone.

**Comment by snoesberger** [comment]
> Hi, i've seen something similiar within Opencast itself before: [opencast/opencast#5366](https://github.com/opencast/opencast/issues/5366) Recently I had the exact same issue again, also directly in Opencast but the plugin uses the same wokflow configuration panel as opencast itself.

I think these are two seperate problems:
1. Starting the duplicate workflow without specifying a date in the input form breaks the event (see also my last comment in https://github.com/opencast/opencast/issues/5366 for a workaround)
2. Workflow parameter checkboxes are not interpreted the same way in the ILIAS plugin as in Opencast (this issue)

**Comment by chfsx** [comment]
@snoesberger I'm unable to add/configure this workflow on my development-machine which uses https://opencast-test.ilub.unibe.ch/ . Or I'm doing it wrong... Can you describe how you add the workflow to the plugin configuration?

**Comment by snoesberger** [comment]
@chfsx first you need to define the correct workflow tags in the plugin configuration. In a standard Opencast installation these are "archive,editor,delete":
![grafik](https://github.com/user-attachments/assets/b92c7aed-58a7-4e83-90e6-d070bdb1ba33)

Then you have to import the workflows into the plugin, now the workflows should be listed and available in ILIAS:
![grafik](https://github.com/user-attachments/assets/326597e3-5697-4897-8489-79ee27cf7c9a)

**Comment by chfsx** [comment]
This took some time to investigate, the more I found, the stranger it got...

Starting the workflow "Duplicate Event" directly in Opencast:

The Form which is presented is exactly the same as in ILIAS, the checkbox looks like this in HTML:

``` 
<input name="configuration.noCopySuffix" id="77c45883-05cf-4f6a-b933-81dec779215a" type="checkbox" class="configField" value="false">
```
The value of the checkbox is "false", this should be the value which gets sent vis POST (more on this later). The checkbox in ILIAS is e.g.  
```
<input id="2_noCopySuffix" name="2[noCopySuffix]" type="checkbox" class="wf-inputs configField" value="false" >
```
as we can see, the value which is sent via POST if the checkbox is checks is "false" as well.

while investigating the communication in Opencast, after sending the submit button, the value of noCopySuffix is no longer "false", it becomes "true":

```
{"mpTitle":"+","seriesId":"+","numberOfEvents":"1","noCopySuffix":"true"}
``` 
(this is what the Opencast GUI sends...)

The ILIAS Plugin sends the value as it is like, 

```
{"mpTitle":"","seriesId":"",,"numberOfEvents":"1","noCopySuffix":"false"}
```

The opencast GUI seems to handle checked checkboxes as "true" and ignored it's value. I will open a PR ASAP which will do the same in ILIAS, but to be honest, this seems completely wrong :-)

**Comment by dagraf** [comment]
Do I understand correctly that Opencast does something weird or even wrong here? Should we not then better open a bug report for Opencast?

**Comment by chfsx** [comment]
i'm not sure about that, it can also just be by definition. so no matter what “value” a checkbox has, it is ignored and the only relevant thing is whether the checkbox was selected or not (which makes sense). i would suggest we implement it that way and then simply test as many workflows as possible that also offer checkboxes in.

it is actually quite strange that a checkbox with the title “Do not use copy suffix” has the value “false”, it would be simpler to have a checkbox with the name “Use copy suffix” with the value “true”.

PR follows shortly

**Comment by chfsx** [comment]
PR in https://github.com/opencast-ilias/OpenCast/pull/366

**Comment by dagraf** [comment]
Fixed with https://github.com/opencast-ilias/OpenCast/pull/366.
