### ISSUE TITLE
Error when adding Unternutzung

### ISSUE THREAD

**Issue by mic-men** [opencast-ilias/OpenCast#357]
**Describe the bug**
Adding an 'Unternutzung' throws an error.

**To Reproduce**
1. In Config o to 'Publikationen' › 'Unternutzungen'
2. Click on 'Hinzufügen', choose (only) channel 'Download'.
3. On execution an error is thrown.

**Expected behavior**
Unternutzung should be created.

**Log**
`Error thrown with message "Class "Init" not found"

Stacktrace:
#15 Error in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Conf/PublicationUsage/class.xoctPublicationSubUsageFormGUI.php:63
#14 xoctPublicationSubUsageFormGUI:__construct in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/Conf/PublicationUsage/class.xoctPublicationUsageGUI.php:291
#13 xoctPublicationUsageGUI:addSub in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:59
#12 xoctGUI:performCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctGUI.php:53
#11 xoctGUI:executeCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/UICore/classes/class.ilCtrl.php:203
#10 ilCtrl:forwardCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.xoctMainGUI.php:115
#9 xoctMainGUI:executeCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/UICore/classes/class.ilCtrl.php:203
#8 ilCtrl:forwardCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/classes/class.ilOpenCastConfigGUI.php:75
#7 ilOpenCastConfigGUI:executeCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/UICore/classes/class.ilCtrl.php:203
#6 ilCtrl:forwardCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php:162
#5 ilObjComponentSettingsGUI:forwardConfigGUI in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Component/classes/Settings/class.ilObjComponentSettingsGUI.php:119
#4 ilObjComponentSettingsGUI:executeCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/UICore/classes/class.ilCtrl.php:203
#3 ilCtrl:forwardCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/Administration/classes/class.ilAdministrationGUI.php:237
#2 ilAdministrationGUI:executeCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/UICore/classes/class.ilCtrl.php:203
#1 ilCtrl:forwardCommand in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /var/www/vhosts/lms-public.uni-tuebingen.de/httpdocs/ilias3/ilias.php:24
`

**Environment:**
 - ILIAS version: 8.14
 - PHP version: 8.0.30
 - Plugin version: 8.2.2 (API Version v1.10.0)
 - Opencast version: 14.6
 - Browser: Firefox

**Additional context**
First tried without having a 'Unternutzungsgruppe'. Then created one. Error occurs in both cases.

**Comment by chfsx** [comment]
Will be fixed in the next version
