### ISSUE TITLE
Code-Style

### ISSUE THREAD

**Issue by chfsx** [opencast-ilias/OpenCast#36]
The Opencast-Plugin uses a legacy code-style which is not really defined. I suggest to have `PSR-2 + X` as the ILIAS-Core uses it. I can provide a PR which changes the style for all classes but this will lead to break all currently open PRs.

Infos for `PSR-2 + X`: https://github.com/ILIAS-eLearning/ILIAS/blob/release_7/docs/development/coding-style.md

**Comment by ebbertd** [comment]
Given that there are not many PRs I don't think that is much of an issue.

**Comment by reiferschris** [comment]
Could we also add this code style check to github actions? Do you have any prior experience for setting that up?

**Comment by chfsx** [comment]
First part see #48

**Comment by chfsx** [comment]
Implemented in #62

**Comment by chfsx** [comment]
New PR in #69

**Comment by dagraf** [comment]
@chfsx Can we close this issue since we have merged several PRs concerning it?

**Comment by chfsx** [comment]
Yes, absolutely. the code style for release_8 and release_9 (upcoming) has been fixed a while ago.
