### ISSUE TITLE
WIth Opencast 16 live streams can no longer be played

### ISSUE THREAD

**Issue by snoesberger** [opencast-ilias/OpenCast#374]
**Describe the bug**
WIth Opencast 16 live streams can no longer be played

**To Reproduce**
1. Plan a live stream in Opencast
2. Try to open live stream in ILIAS Paella player
3. See error message: "Undefined array key "search-result""

**Expected behavior**
Live streams play correctly.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/6fe1b2b5-583e-4f71-82f2-1c34a421b513)

**Environment (please complete the following information):**
 - ILIAS version: 8
 - Plugin version: 8.1.4
 - Opencast version 16.7

**Additional context**
With Opencast 16 the return values for the API endpoints /search/series.json and /search/episode.json have changed:

- < OC 16: ['search-results']['result']['mediapackage']
- \>= OC 16: ['result'][0]['mediapackage']

**Comment by dagraf** [comment]
@snoesberger : Can you please test the fix to this issue? Thx!

https://github.com/opencast-ilias/OpenCast/issues/374
