### ISSUE TITLE
Missing series ID

### ISSUE THREAD

**Issue by ebbertd** [opencast-ilias/OpenCast#42]
**Describe the bug**
Starting with version 4 of the plugin the series ID is no longer shown within the settings of an object.

**To Reproduce**
1. Create a new object
2. Go to settings
3. Scroll down to the bottom
4. The series ID is not shown

**Expected behavior**
The series ID should be stated there, as in previous versions of the plugin. Although stating the series ID in the info tab might make more sense.

**Screenshots**
In 3.7.x
![Screenshot 2022-05-19 at 13-09-45 ILIAS Uni Köln Opencast Webinar am 10 09 2021](https://user-images.githubusercontent.com/20522234/169280925-847881f4-ab31-4c23-bb8d-099c070971ee.png)

In tested version (see below):
![Screenshot 2022-05-19 at 13-10-04 ILIAS Referenzvideos](https://user-images.githubusercontent.com/20522234/169281130-6ce9a7e4-f300-4edf-a351-aeff55e8c172.png)

**Environment (please complete the following information):**
 - ILIAS version: v6.15 2022-02-02
 - PHP version: PHP 7.4.3 (cli)
 - Plugin version: 4.x commit: bdbdceaa534501b55b1b748a776b9bcbd96cdc66
 - Browser: Firefox

**Comment by dagraf** [comment]
I tested this bug on our ILIAS and can confirm it.

**Comment by chfsx** [comment]
The background is as follows: in opencast, the form was changed from the old ilPropertyFormGUI to the new UI\Forms from ILIAS a long time ago. in the new forms, there is no longer an "input" type that simply displays something. in the old forms, there was the ilNonEditableInputGUI for this purpose.

Therefore, from my point of view, the issue must be closed, as there is no way to implement this at present.

**Comment by dagraf** [comment]
That's a shame. There is no way at all or just no short way?

**Comment by chfsx** [comment]
not a way that i can justify. basically you can always do everything :-) but the question is whether you want to maintain an additional 50-100 lines of code to do that. by the way, that would be exactly the kind of case that breaks like in #282 if something changes in the core.

**Comment by dagraf** [comment]
Thx for the further informations. Accordingly, I am closing this ticket 'with a heavy heart'.
