### ISSUE TITLE
Missing configuration: In sub-tab "Events" the option '"Presenter" mandatory' is missing

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#49]
**Describe the bug**
In version v4.0.1 the (relatively new) option to make the '"Presenter" mandatory' is missing.

**To Reproduce**
1. Go to the configuration of the plugin
2. Open tab 'Settings' and there the sub-tab 'Events'
3. Scroll down to the very bottom of the screen
4. There the option "Presenter" mandatory' should be offered.

**Expected behavior**
Offer again the option "Presenter" mandatory' with explanation "Makes field "Presenter" mandatory for an event upload".

**Screenshots of v3.6.1**
<img width="511" alt="Bildschirmfoto 2022-06-20 um 20 10 28" src="https://user-images.githubusercontent.com/15246287/174658690-fcd6d1a3-18fa-4675-89fa-66ac0f44af3b.png">

**Environment (please complete the following information):**
 - ILIAS version: v7.10 2022-04-28
 - PHP version: PHP ???
 - Plugin version: 4.0.1
 - Browser: Firefox

**Comment by dagraf** [comment]
@reiferschris Might this be the case because it is now configurable which metadata can be offered when editing/creating a series or when editing metadata of an event or when uploading a new event? If so, please close this issue.

**Comment by DZenker** [comment]
Yes, it's not a bug, it's a feature, as this is now configurable in the metadata section of the plugin:

![4 0x-Plugin-OpenCast - Metadata Setting](https://user-images.githubusercontent.com/5229751/174734129-b2dd288a-3bc4-4607-936f-365b3f1c046d.png)
![4 0x Plugin - Creator Metadata (required)](https://user-images.githubusercontent.com/5229751/174734133-c0b06577-fa5d-4efe-9ff0-b1a6c440fbfc.png)
.

**Comment by dagraf** [comment]
Perfect. Thx for the explanation. I close this issue.
