### ISSUE TITLE
Missing configuration: Options to specify Licenses and 'License info' are missing

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#51]
**Describe the bug**
In v4.0.1 there is no longer a possibility to specify under which licenses the series is published and to offer more information about the licenses ('License info'). In older versions (e.g., v3.6.1) this possiblity was offered in the sub-tag 'Series' of the tab 'Settings'. This sub-tab does not longer exist and seems to be replaced by sub-tab 'Terms of use'.

**To Reproduce**
1. Go to the configuration of the plugin
2. Open tab 'Settings' and there the sub-tab 'Terms of Use'
3. There the option "" and "License Info" should be offered.
4. Because they are not when creating a Opencast series in ILIAS the options for 'License' with its description are missing

**Expected behavior**
Offer again the options "Licenses" and the options "License Info".

**Screenshots**
v3.6.1:
<img width="892" alt="Bildschirmfoto 2022-06-20 um 20 28 40" src="https://user-images.githubusercontent.com/15246287/174661537-c0c37672-1cc1-4fed-be45-e01ddcff3033.png">
<img width="1196" alt="Bildschirmfoto 2022-06-20 um 21 48 43" src="https://user-images.githubusercontent.com/15246287/174669306-7aad9265-0998-4c7c-a03c-4c923e949668.png">

v.4.0.1:
<img width="1183" alt="Bildschirmfoto 2022-06-20 um 20 28 55" src="https://user-images.githubusercontent.com/15246287/174661550-e378ef02-a759-4b81-b620-93b7fe57c73d.png">
<img width="855" alt="Bildschirmfoto 2022-06-20 um 21 49 18" src="https://user-images.githubusercontent.com/15246287/174669287-defa8d4b-2719-4659-9c12-053183e031e3.png">

**Comment by ebbertd** [comment]
The licenses are supposed to be part of the Opencast Metadata now. However, sadly the work on this has not been finished yet.

**Comment by dagraf** [comment]
> The licenses are supposed to be part of the Opencast Metadata now. However, sadly the work on this has not been finished yet.

Aus Community-Meeting: Kriegt man momentan nicht über die API.

Fazit: Die vorherige Lösung implementieren. Beliebige Infos die man schickt, werden von OC angenommen.

**Comment by dagraf** [comment]
After deploying https://github.com/opencast-ilias/OpenCast/pull/126 with okaufmanns' suggestions:

- The licences can be correctly selected but they do NOT get set in Opencast. This should be the case.
- In config: Please place the two textboxes "Licenses" and "Licence info" at the very bottom of the subtab "Terms of Use"

**Comment by dagraf** [comment]
Licenses can be specified in the subtab "Series" (see in tab "Metadata"). Therefore, I close this issue.

**Comment by dagraf** [comment]
> Where can I configure this in the current PlugIn version?
> 
> ![03](https://user-images.githubusercontent.com/118901635/246109663-828a0ff9-74c1-4f5d-8799-e2b1f1e08b24.jpg)
> 
> Environment:
> 
> ```
> ILIAS version: v7.22 2023-05-31
> PHP version: 7.3
> Plugin version: 5.1.1
> Opencast version 13.0.0 (educast.nrw)
> Browser: firefox, chrome
> ```

I do not understand your question. Because after updating to the versions of Opencast (13) and ILIAS-Plugin (5.1.1) I can still see this configuration option at the same place.

**Comment by ralede** [comment]
I have found the series subtab now. Sorry!
