### ISSUE TITLE
Missing configuration: Three options in sub-tab 'Advanced' are missing

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#52]
**Describe the bug**
In version v4.0.1 in the sub-tab 'Advanced' (tab 'Settings') the options  to make the 'Request combination level', 'Without metadata' and 'Upload chunk size (MB)' are missing.

**To Reproduce**
1. Go to the configuration of the plugin
2. Open tab 'Settings' and there the sub-tab 'Advanced'
3. There the options 'Request combination level', 'Without metadata' and 'Upload chunk size (MB)' should be offered.

**Expected behavior**
 Make these options configurable again.

**Screenshots**
v3.6.1:
<img width="896" alt="Bildschirmfoto 2022-06-20 um 21 29 25" src="https://user-images.githubusercontent.com/15246287/174667974-b194358a-288f-4def-9fd0-35932637a088.png">

v4.0.1:
<img width="1187" alt="Bildschirmfoto 2022-06-20 um 21 29 33" src="https://user-images.githubusercontent.com/15246287/174667790-eb5a2d69-2878-4152-94a5-4410c9a3bf69.png">

**Additional context**
The options 'Request combination level' and 'Without metadata' were integrated into the plugin quite some time ago (3-4 years). Maybe there are of no (great) use anymore.

**Comment by DZenker** [comment]
The option "Upload chunk size" was probably removed because chunk upload is no longer used (#27).

**Comment by dagraf** [comment]
In my opinion chunk upload should be integrated again.

**Comment by chfsx** [comment]
@dagraf I wouldn't necessarily do this configuratively. in the new proposed upload, half of the upload-limit (php) is used for the chunks. doing this configuratively also runs the risk of defining a larger chunk-size than is even possible (larger than upload-limit) or you would have to check this.

**Comment by dagraf** [comment]
@chfsx Thx for the explanation. 

@all: I would also assume that the other two missing configuration options can be neglected and therfore I close this issue. Please feel free to reopen it if your see otherwise.

**Comment by dagraf** [comment]
I'm reopening this issue since the two missing options ('Request combination level', 'Without metadata') could be responsible for the experienced poor behavior (see https://github.com/opencast-ilias/OpenCast/issues/80).

**Comment by okaufman** [comment]
The option "Without metadata" seems to be the default in the new plugin Version. 
In the older Version there used to be two api-calls when reloading the events of a series 
(the first call with "withmetadata=false", the second call with "withmetadata=true") 
In the new Version per default only one API-call ( with "withmetadata=true") is made.

The question is are there installation who still uses an older Opencast-Api (older than 1.1.0). They would need to be able to send two api-calls and configure that somewhere.

**Comment by okaufman** [comment]
The same goes for the "Request Combination Level" per defautl the new Version uses the same configuration that would be used with "Event + ACL + MD + PUB" the call looks something like that "https://OPENCASTSERVER.ch/api/events?filter=series%OPENCAST_SERIES_ID&offset=0&limit=1000&withmetadata=true&withacl=true&withpublications=true&withscheduling=true)"
Using a different config in the old version would have led to several API-calls from ilias.

the default api-calls of the new version are excatly how Uni Bern would like to configure the plugin.

**Comment by dagraf** [comment]
Thx for taking a look at the code. For a start please edit the only API-call in the new version to "withmetadata=false". I assume that this will fix the performance issue.

That installations using older Opencast-Api versions would no longer work can be tolerated in my opinion, as the 1.1.0 was introduced more than 4 years ago. I'd say we take care of this in some kind of release note that this version of the plugin requires OC-API to be 1.1.0 or newer.

**Comment by dagraf** [comment]
I close this issue as performance problems could be solved and were not caused by the missing configuration options.
