### ISSUE TITLE
Wrong timezones in ilias plugin

### ISSUE THREAD

**Issue by xJuvi** [opencast-ilias/OpenCast#60]
**Describe the bug**
Hey there,
Today we updated our ilias from version 5.4.x to version 7.0.x. The Opencats plugin also had to be updated from version 3.6.0 to version 4.0.0.

Now we have problems with the time format. All times are shown in UTC +0. This is not critical for recordings and uploads. The problem, however, is that this is also the case with live streams. Opencats already receives an incorrect timestamp when it is created. I scheduled a stream for 4:30 p.m., Opencast created this as 6:30 p.m. and also transmitted it to extron. Due to the error, the stream cannot be accessed via Ilias, as at 6:30 p.m. Ilias believes the recording is in the past, but at 4:30 p.m. finds no recording. Something about the timestamp was changed in commit https://github.com/opencast-ilias/OpenCast/commit/80729bb0d8adcddb4d5855566a17c87408c04f3a - is this the error? Can anyone else reproduce the error?

Existing recordings are also displayed in UTC +0 in ilias.

**To Reproduce**
1. Create a new event in an exist series
2. Enter the planned start time
3. Check the time stored in Opencast
4. Compare the timestamps

**Screenshots**
Example one:
![image](https://user-images.githubusercontent.com/31671206/178286051-be3cd011-a676-4483-a1f6-91ef03309d9d.png)
![image](https://user-images.githubusercontent.com/31671206/178286177-4e11b663-2c36-418b-92c8-6577e09c5ae5.png)
![image](https://user-images.githubusercontent.com/31671206/178286245-21ef7413-5b07-4b4c-a439-5b3cecca2d79.png)

Example two:
Planning in Ilias:
![image](https://user-images.githubusercontent.com/31671206/178287193-a3f93ada-e025-434c-97e3-1350f6821a0b.png)
On Opencast:
![image](https://user-images.githubusercontent.com/31671206/178287261-290722b9-c234-4e37-ac29-b99ae545d7fe.png)
On extron:
![image](https://user-images.githubusercontent.com/31671206/178287531-9ad81815-94de-442a-b233-6dc5c31aae20.png)
On Ilias series:
![image](https://user-images.githubusercontent.com/31671206/178287770-fa4b7e58-010a-4eeb-80b6-bbf5326f975b.png)

Example three:
![image](https://user-images.githubusercontent.com/31671206/178291278-86e7a5d1-004f-4d78-a9df-fba6c477cfc1.png)

**Environment (please complete the following information):**
 - ILIAS version: 7.11 2022-06-29
 - PHP version: 7.4.30
 - Plugin version: 4.0.0
 - Browser: Google Chrome 102.x

**Comment by xJuvi** [comment]
Hi there,

some more information:
- Ilias and Opencast Server are running in UTC+2

**create scheduled event**
- Input field: UTC +2  :white_check_mark:
- after sumit value changed to UTC +4 :x:

**eventlist**
- Date in table view displayed as UTC +2  :white_check_mark:
https://github.com/opencast-ilias/OpenCast/blob/6d20811f3c8c30aaffc28f4a33d2b9f08ee5247a/classes/Event/class.xoctEventTableGUI.php#L166
- Date in title view (boxes) displayed as UTC +0 :x:
https://github.com/opencast-ilias/OpenCast/blob/6d20811f3c8c30aaffc28f4a33d2b9f08ee5247a/classes/Event/class.xoctEventTileGUI.php#L124 

**edit events**
- input field in editor: UTC +2  :white_check_mark:
- after submit value changed to UTC+4  :x:

**conclusion**
Opencast stores all dates as UTC+0. The OC plugin in ilias gets the UTC+0 values und caches them in the database (cache enabled). On some places, the date(time) will be converted in the ilias default timezone. Other places format only the opencast utc+0 date and display the date(time) in the wrong timezone.

**Comment by reiferschris** [comment]
Hi, thank you for reporting this issue. I also ran in this problem and thought it might be my environment. I noticed this while testing this fix: https://github.com/opencast-ilias/OpenCast/pull/40
Unfortunately the current version still has some bugs that we hope to resolve soon.

**Comment by dagraf** [comment]
I did a retest and can confirm this bugfix.

**Comment by samuelinniger** [comment]
There is the same problem as well when scheduling over API (+1h gets scheduled on the initial time) @okaufman
