### ISSUE TITLE
Additionally to the role any number of 'additional ACL actions' should be able to add when autorising users via the API

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#67]
**Description**
When a series is created or settings of a series get saved or a ILIAS administrator opens a video in the video editor all users with enough rights (right "Edit videos" is activated) get authorized in Opencast. This means their user role gets inserted in the series' ACLs with read and wright rights. In order to give those administrators also the necessary administrator rights in the annotation tool, additional ACL actions must be added to their user role. In the case of the University of Bern we add 'annotate' and 'annotate-admin'.

**Possible solution**
In addition to the user role with read and write rights it should be configurable which additional ACL actions get added to authorized users when granting them rights on a series using the API. Important: The user role with the additional ACL actions must be added to the series, not to single videos.
Therefore, please add an additional configuration option (see below for location, title and description) to set any number of additional ACL actions which a user reveives when he is granted permisions on a series in Opencast.

_Location_
In the tab "Settings" and there in the subtab "Groups & Roles", right below "Prefix for user roles (mapping is attached)" (see screenshot)
![Bildschirmfoto 2022-08-17 um 15 16 24](https://user-images.githubusercontent.com/15246287/185143721-ef3312e0-b9a5-4cbc-a8a9-c7f295ee743e.png)

_Title:_
DE: Zusätzliche ACL Aktionen
EN: Additional ACL actions

_Description:_
DE: Wenn ein User Zugriffsrechte auf einer Serien in Opencast bekommt, werden diese Werte als zusätzliche ACL Aktionen gesetzt (in Opencast eingetragen im Tab "Zugriffsrechte" in der Spalte "Weitere Aktionen").
EN: If a user is granted permissions on a series in Opencast, these values are set as additional ACL actions (visible in Opencast in the tab "Permissions" in the column "Additional actions").

**Comment by reiferschris** [comment]
We already established that we have common interests here. 
In my opinion it would be worth considering granting these additional privileges via RBAC as suggested here: https://github.com/opencast-ilias/OpenCast/issues/14
At least this idea should be kept in mind when implementing a first version of this feature. Those privileges would also be added on a per-user basis as proposed, but the granted privileges would also be visible and editable inside ilias.

**Comment by dagraf** [comment]
Lets also discuss this in our next meeting. In my opinion, some of the new right management options could be handled directly in ILIAS without transfering roles to Opencast (for example, "Download").

**Comment by dagraf** [comment]
Feature is implemented. Therefore, I close this ticket.
