### ISSUE TITLE
Poor performance: Opening and reloading a series takes way to long

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#80]
**Describe the bug**
When testing the plugin on our test platform we did not have any performance problems, but there we haven't many events on this Test-Opencast. Now we are running tests with our productive plattform (ILIAS and Opencast) and opening a series takes way to long. This is also true  for "Reloading Events" or when I use the pagination. Hand stopped times:

- Series with 3 recordings: 10 seconds
- Series with 21 recordings: 75 seconds
- Series is fast (https://ilias-next.unibe.ch/goto_ilias3_unibe_xoct_2576918.html)

**To Reproduce**
1. Have the plugin running in an environment with a lot of videos
2. Open a series with one or more event
3. Reload events in a series with one or more event
4. Use pagination in a series with more than 10 events

**Expected behavior**
The series should open fast.

**Environment (please complete the following information):**
 - ILIAS version: v7.11 2022-06-29
 - Plugin version: 5.0.0
 - Browser: Firefox

**Additional context**
Possibly this poor performance is due to two configuration options that are missing ('Request combination level', 'Without metadata') since the refactoring done by fluxlabs (see https://github.com/opencast-ilias/OpenCast/issues/52).

**Comment by dagraf** [comment]
Can anybody confirm such performance issues? Or does it react fast on your installations?

**Comment by reiferschris** [comment]
This might be the core issue and a fix: https://github.com/opencast/opencast/pull/4417
Can't test this at the moment but hopefully soon.

**Comment by reiferschris** [comment]
From what I gathered in the opencast matrix group @mtneug applied the fix mentioned above to production already and saw a significant improvement in performance, is that right?

**Comment by dagraf** [comment]
I did a retest and can confirm the bugfix.
