### ISSUE TITLE
Sort function (A-Z) does not work properly in the column "Speaker" (5.0.0)

### ISSUE THREAD

**Issue by samuelinniger** [opencast-ilias/OpenCast#99]
**Describe the bug**
Sort function (A-Z) does not work properly in the column "Speaker"

**To Reproduce**
1. Go to a Opencast Video Series in ILIAS
2. Click on the Column title "Speaker"

**Expected behavior**
The metadata should be properly sorted A-Z. This is not the case.

**Screenshots**
<img width="1151" alt="grafik" src="https://user-images.githubusercontent.com/60101424/202695792-14aa38c9-905e-445f-aeb7-2e03cc74a009.png">

**Log**
If you have it please attach the relevant log.

**Environment (please complete the following information):**

    ILIAS version: v7.11 2022-06-29
    Plugin version: 5.0.0
    Browser: Firefox
    Opencast: 11.0.0.

**Additional context**

**Comment by chfsx** [comment]
How can I configure the plugin to have a column "Speaker"? I do not have this...

**Comment by okaufman** [comment]
![Bildschirmfoto 2023-06-28 um 11 22 58](https://github.com/opencast-ilias/OpenCast/assets/41621260/46e36219-c649-4073-8913-03793b9bf9c2)

This can be configured as a Metadata-Field under Metadata -> Events

**Comment by Amstutz** [comment]
thx alot @chfsx for providing a fix for this one.
